namespace DocWizz.Tests.Journey;

// Exercises the real CLI and file ownership, not only argument parsing.
public class ProductJourneyTests
{
    const string Template = """
        schema: 1
        product_id: sw-architecture
        xt_variant: V-Modell XT
        xt_version: '2.4'
        tailoring: project-specific
        sections:
          - id: scope
            title: Scope
            required: true
            sources: [project]
        """;

    [Fact]
    public void Product_is_idempotent_preserved_by_generate_and_never_overwrites_manual_content()
    {
        using var repo = new Sources(("template.yaml", Template), ("Example.cs", "public class Example {}"));
        var first = Docwizz.Run("product", repo.Root, Path.Combine(repo.Root, "template.yaml"));
        Assert.Equal(0, first.Exit);
        var output = Path.Combine(repo.Root, "docs", "products", "sw-architecture.md");
        Assert.True(File.Exists(output));
        var original = File.ReadAllText(output);
        Assert.StartsWith("<!-- generated by docwizz product -->", original);

        var second = Docwizz.Run("product", repo.Root, Path.Combine(repo.Root, "template.yaml"));
        Assert.Equal(0, second.Exit);
        Assert.Contains("unchanged:", second.Out);
        Assert.Equal(original, File.ReadAllText(output));

        var generated = Docwizz.Run("generate", repo.Root);
        Assert.Equal(0, generated.Exit);
        Assert.Equal(original, File.ReadAllText(output));

        File.WriteAllText(output, "# manually written\n");
        var blocked = Docwizz.Run("product", repo.Root, Path.Combine(repo.Root, "template.yaml"));
        Assert.Equal(1, blocked.Exit);
        Assert.Equal("# manually written\n", File.ReadAllText(output));
    }

    [Fact]
    public void Invalid_template_and_traversal_identifiers_fail_without_writing()
    {
        using var repo = new Sources(("template.yaml", Template.Replace("sw-architecture", "../../README")));
        var result = Docwizz.Run("product", repo.Root, Path.Combine(repo.Root, "template.yaml"));
        Assert.Equal(1, result.Exit);
        Assert.Contains("product_id", result.Err);
        Assert.False(Directory.Exists(Path.Combine(repo.Root, "docs", "products")));
    }
}
