using System.Text;
using System.Text.RegularExpressions;
using System.Xml.Linq;

// Writes the docs/ tree. Everything here is derived from the model; nothing is hand-maintained.
partial class Generator(string root, string outDir, CodeModel model, List<DocumentationItem> findings, ArchitectureResult arch, Config config,
    Dictionary<string, string> drafts)
{
    public const string Marker = "<!-- generated by docwizz: edits are overwritten -->";
    static readonly string[] TopKinds = ["class", "record", "struct", "interface", "type", "enum", "delegate", "component", "module", "store"];
    const int MaxDiagramEdges = 60;

    readonly ArchitectureConfig archConfig = config.Architecture;
    readonly Dictionary<string, Node> nodes = model.Nodes.ToDictionary(n => n.Id);
    readonly Dictionary<string, string> parent = model.Edges.Where(e => e.Kind == "contains").ToDictionary(e => e.To, e => e.From);
    readonly ILookup<string, string> children = model.Edges.Where(e => e.Kind == "contains").ToLookup(e => e.From, e => e.To);
    readonly ILookup<string, string> implOf = model.Edges.Where(e => e.Kind == "implements").ToLookup(e => e.From, e => e.To);
    readonly Dictionary<string, DocumentationItem> findingOf = findings.ToDictionary(f => f.Node.Id);

    public List<string> Run()
    {
        Directory.CreateDirectory(Path.Combine(outDir, "modules"));
        Directory.CreateDirectory(Path.Combine(outDir, "views"));
        // Remove only pages we generated earlier, so renamed/deleted modules don't linger.
        foreach (var f in Directory.EnumerateFiles(outDir, "*.md", SearchOption.AllDirectories))
            if (File.ReadLines(f).FirstOrDefault() == Marker) File.Delete(f);

        var written = new List<string>();
        void Write(string rel, string body)
        {
            File.WriteAllText(Path.Combine(outDir, rel), $"{Marker}\n{body}");
            written.Add(rel);
        }

        var modules = model.Nodes.Where(n => n.Kind is not ("route" or "project" or "package" or "external" or "config") || parent.ContainsKey(n.Id))
            .GroupBy(n => Folder(n.File)).OrderBy(g => g.Key).ToList();
        foreach (var m in modules) Write($"modules/{Slug(m.Key)}.md", Module(m.Key, m.ToList()));
        Write("index.md", Index(modules.Select(m => m.Key).ToList()));
        Write("architecture.md", ArchitecturePage(modules.Select(m => m.Key).ToList()));
        Write("api.md", Api());
        Write("frontend.md", FrontendPage());
        Write("quality.md", Quality());
        foreach (var (page, _, body) in Views()) Write($"views/{page}.md", body());
        Write("architecture-description.md", DescriptionPage());
        return written;
    }

    string Index(List<string> modules)
    {
        var sb = new StringBuilder();
        var kinds = model.Nodes.GroupBy(n => n.Kind).ToDictionary(g => g.Key, g => g.Count());
        sb.AppendLine($"# {Path.GetFileName(Path.GetFullPath(root))}\n");
        sb.AppendLine($"Generated from commit `{model.Commit ?? "unknown"}`.\n");
        sb.AppendLine("| | |\n|---|---|");
        foreach (var (label, kind) in new[] { ("Classes & records", "class"), ("Methods", "method"), ("Frontend functions", "function") })
        {
            var n = kind == "class" ? kinds.GetValueOrDefault("class") + kinds.GetValueOrDefault("record") : kinds.GetValueOrDefault(kind);
            if (n > 0) sb.AppendLine($"| {label} | {n} |");
        }
        sb.AppendLine($"| Documentation coverage (profile `{config.Profile}`) | {Analyzer.Coverage(findings):0}% |");
        sb.AppendLine($"| Critical documentation gaps | {findings.Count(Analyzer.IsCritical)} |");
        sb.AppendLine($"| Architecture violations / cycles | {arch.Violations.Count} / {arch.Cycles.Count} |\n");
        if (drafts.Count > 0)
            sb.AppendLine($"🤖 marks {drafts.Count} AI-drafted summaries for code that has no docs yet — review them, then move them into the code.\n");
        sb.AppendLine("- [Architecture description](architecture-description.md)\n- [Architecture](architecture.md)\n- [API endpoints](api.md)\n" +
            "- [Frontend](frontend.md)\n- [Quality](quality.md)\n");
        if (Technology().ToList() is { Count: > 0 } tech)
            sb.AppendLine("## Technology\n\n" + string.Join("\n", tech.Select(t => $"- {t}")) + "\n");
        var blocks = Roles.Select(r => (r.Label, Count: model.Nodes.Count(n => n.Kind == r.Match || n.Tags?.Contains(r.Match) == true)))
            .Where(r => r.Count > 0).ToList();
        if (blocks.Count > 0)
            sb.AppendLine("## Building blocks\n\n| Role | Count |\n|---|---|\n" + string.Join("\n", blocks.Select(b => $"| {b.Label} | {b.Count} |")) + "\n");
        sb.AppendLine("## Modules\n");
        foreach (var m in modules) sb.AppendLine($"- [{m}](modules/{Slug(m)}.md) — {Layer(m) ?? "no layer"}");
        return sb.ToString();
    }

    // Kind or tag → label, in reading order (backend, then frontend).
    static readonly (string Label, string Match)[] Roles = [("Controllers", "controller"), ("API endpoints", "endpoint"),
        ("Services", "service"), ("Repositories", "repository"), ("Entities", "entity"), ("DbContexts", "dbcontext"),
        ("Background services", "background-service"), ("Hosted services", "hosted"), ("Middleware", "middleware"), ("SignalR hubs", "hub"), ("Options", "options"),
        ("Vue components", "component"), ("Views", "view"), ("Stores", "store"), ("Composables", "composable"), ("Routes", "route")];

    // Well-known packages → what they tell a reader about the stack. Anything else is in views/context.md.
    // ponytail: a short curated list; extend it (or read it from config) when a project's stack goes unnamed.
    static readonly (string Package, string Label)[] KnownPackages = [
        ("Microsoft.EntityFrameworkCore.SqlServer", "Entity Framework Core, SQL Server"),
        ("Npgsql.EntityFrameworkCore.PostgreSQL", "Entity Framework Core, PostgreSQL"),
        ("Microsoft.EntityFrameworkCore.Sqlite", "Entity Framework Core, SQLite"),
        ("Pomelo.EntityFrameworkCore.MySql", "Entity Framework Core, MySQL"),
        ("Microsoft.EntityFrameworkCore", "Entity Framework Core"), ("Dapper", "Dapper"), ("Npgsql", "PostgreSQL"),
        ("MediatR", "MediatR"), ("MassTransit", "MassTransit"), ("Hangfire.Core", "Hangfire"), ("Serilog", "Serilog"),
        ("Swashbuckle.AspNetCore", "Swagger / OpenAPI"), ("Microsoft.AspNetCore.OpenApi", "OpenAPI"),
        ("Microsoft.AspNetCore.SignalR", "SignalR"), ("vue", "Vue"), ("nuxt", "Nuxt"), ("pinia", "Pinia"), ("vuex", "Vuex"),
        ("vue-router", "Vue Router"), ("axios", "axios"), ("vite", "Vite"), ("vuetify", "Vuetify"), ("quasar", "Quasar"),
        ("primevue", "PrimeVue"), ("element-plus", "Element Plus"), ("typescript", "TypeScript")];

    // From the project files only: SDK, target frameworks, well-known packages with their declared version.
    IEnumerable<string> Technology()
    {
        foreach (var p in model.Nodes.Where(n => n.Kind == "project" && n.Tags?.Contains("dotnet") == true))
        {
            var sdk = p.Tags!.FirstOrDefault(t => t.StartsWith("Microsoft.NET.Sdk"));
            var kind = sdk switch
            {
                "Microsoft.NET.Sdk.Web" => "ASP.NET Core", "Microsoft.NET.Sdk.Worker" => ".NET worker",
                "Microsoft.NET.Sdk.Razor" => "Razor class library", "Microsoft.NET.Sdk.BlazorWebAssembly" => "Blazor WebAssembly",
                _ => ".NET",
            };
            var tfms = p.Tags!.Where(t => t.StartsWith("net")).ToList();
            var role = p.Tags!.FirstOrDefault(t => t is "executable" or "library" or "test");
            var folder = p.Tags!.FirstOrDefault(t => t.StartsWith("sln:"))?[4..];
            yield return $"`{p.Name}`: {kind}{(tfms.Count > 0 ? $" on {string.Join(", ", tfms)}" : "")}" +
                (role is null ? "" : $" — {role}") + (folder is null ? "" : $", solution folder `{folder}`");
        }
        var versions = model.Edges.Where(e => e.Kind == "depends-on").GroupBy(e => e.To).ToDictionary(g => g.Key, g => g.First().Label);
        var packages = model.Nodes.Where(n => n.Kind == "package").ToDictionary(n => n.Name, n => n.Id);
        var named = new List<string>();  // "Entity Framework Core, PostgreSQL" already names EF Core and PostgreSQL
        foreach (var (package, label) in KnownPackages)
            if (packages.TryGetValue(package, out var id) && !named.Any(l => l.Contains(label)))
            {
                named.Add(label);
                yield return versions.GetValueOrDefault(id) is { } v ? $"{label} ({v})" : label;
            }
    }

    string ArchitecturePage(List<string> modules)
    {
        var sb = new StringBuilder("# Architecture\n\n");
        // Layer graph: any HTTP call is a dependency on `http`. Module graph: HTTP calls point at the endpoint's module.
        var deps = Dependencies().Select(d => (From: Folder(nodes[d.From].File),
            To: nodes.TryGetValue(d.To, out var t) ? Folder(t.File) : null, Http: d.Kind == "http")).ToList();

        sb.AppendLine("Views: " + string.Join(" · ", Views().Select(v => $"[{v.Title}](views/{v.Page}.md)")) + "\n");
        sb.AppendLine("## Layers\n");
        sb.AppendLine("Actual dependencies between layers (edge label = number of references). Allowed per config: ");
        sb.AppendLine(string.Join(", ", archConfig.Allow.Select(kv => $"`{kv.Key} → {(kv.Value.Count > 0 ? string.Join("/", kv.Value) : "∅")}`")) + ".\n");
        var layerEdges = arch.LayerDependencies.Select(d => (d.From, d.To, d.Count));
        sb.AppendLine(Mermaid("graph TD", layerEdges, x => x));

        sb.AppendLine("## Modules\n");
        var moduleEdges = deps.Where(d => d.To is not null && d.To != d.From)
            .GroupBy(d => (d.From, To: d.To!)).Select(g => (g.Key.From, g.Key.To, g.Count())).ToList();
        sb.AppendLine(moduleEdges.Count <= MaxDiagramEdges * 2
            ? Mermaid("graph LR", moduleEdges, x => x)
            : $"_{moduleEdges.Count} module dependencies — too many to draw; see each module page._\n");

        sb.AppendLine($"## Violations ({arch.Violations.Count})\n");
        if (arch.Violations.Count == 0) sb.AppendLine("None.\n");
        else
        {
            sb.AppendLine("| Rule | Layers | Severity | From | To | Example |\n|---|---|---|---|---|---|");
            foreach (var v in arch.Violations.OrderByDescending(v => v.Severity))
                sb.AppendLine($"| {v.Rule} | {v.FromLayer} → {v.ToLayer} | {v.Severity.ToString().ToLowerInvariant()} | {SourceLink(v.FromFile, "")} | `{v.To}` | {Esc(v.Example)} |");
            sb.AppendLine();
        }
        sb.AppendLine($"## Cycles ({arch.Cycles.Count})\n");
        foreach (var c in arch.Cycles) sb.AppendLine($"- {string.Join(" ↔ ", c.Select(m => $"[{m}](modules/{Slug(m)}.md)"))}");
        if (arch.Cycles.Count == 0) sb.AppendLine("None.");
        return sb.ToString();
    }

    string Api()
    {
        var sb = new StringBuilder("# API endpoints\n\n");
        var callers = model.Edges.Where(e => e.Kind == "http").ToLookup(e => e.To, e => e.From);
        var endpoints = model.Nodes.Where(n => n.Tags?.Contains("endpoint") == true)
            .OrderBy(n => n.Route?.TrimStart('/')).ThenBy(n => n.Tags![1]).ToList();
        sb.AppendLine("| Method | Route | Summary | Input | Response | Authorization | Handler | Called from |\n|---|---|---|---|---|---|---|---|");
        foreach (var n in endpoints)
        {
            var from = callers[n.Id].Select(c => nodes.TryGetValue(c, out var cn) ? $"`{cn.Name}`" : c).Distinct();
            var input = string.Join("<br>", (n.Parameters ?? []).Select(p => $"`{Esc(p)}`"));
            var auth = n.Tags!.Contains("anonymous") ? "anonymous" : n.Tags.Contains("authorize") ? "required" : "—";
            sb.AppendLine($"| {n.Tags![1]} | `/{n.Route?.TrimStart('/')}` | {Esc(Summary(n) ?? "—")} | {(input == "" ? "—" : input)} | " +
                $"{Response(n)} | {auth} | {SourceLink(n.File, n.Line, $"{Path.GetFileName(n.File)}:{n.Line}")} | {string.Join(", ", from)} |");
        }
        // Middleware in registration order, per place that configures it (a project's top-level code, Startup.Configure).
        foreach (var g in model.Edges.Where(e => e.Kind == "pipeline").GroupBy(e => e.From))
        {
            var at = nodes.TryGetValue(g.Key, out var owner) ? owner.Kind == "project" ? $"project `{owner.Name}`" : $"`{Display(owner)}`" : g.Key;
            sb.AppendLine($"\n## Request pipeline ({at})\n\nMiddleware in the order it is registered; each request passes through it top to bottom.\n");
            var i = 0;
            foreach (var e in g)
                sb.AppendLine($"{++i}. {(nodes.TryGetValue(e.To, out var m) ? $"{ModuleLink(m)} (`UseMiddleware`)" : $"`{e.To["pipeline:".Length..]}`")}");
        }
        // Each endpoint's path: frontend callers → endpoint → handler (controller) → services → data → external systems.
        var flowLines = new List<string>();
        var flowEdges = new List<(string From, string To, int Count)>();
        foreach (var n in endpoints)
        {
            var trace = Trace(n.Id);
            var handler = parent.TryGetValue(n.Id, out var owner) ? owner : null;
            var label = EndpointLabel(n);
            foreach (var c in callers[n.Id].Where(nodes.ContainsKey)) flowEdges.Add((nodes[c].Name, label, 0));
            if (handler is not null) flowEdges.Add((label, nodes[handler].Name, 0));
            foreach (var (from, to) in trace.Steps)
                flowEdges.Add((from == n.Id ? handler is null ? label : nodes[handler].Name : UnitLabel(from), UnitLabel(to), 0));
            if (trace.Layers.Count == 0) continue;
            var data = Reached(trace, x => x.Tags?.Contains("dbcontext") == true).Select(x => x.Name).ToList();
            var external = Reached(trace, x => x.Kind == "external").Select(ExternalLabel).ToList();
            flowLines.Add($"- `{label}`: {(handler is null ? "" : $"{nodes[handler].Name} → ")}{Esc(Chain(trace))}" +
                (data.Count + external.Count > 0 ? $"  \n  _data:_ {(data.Count > 0 ? string.Join(", ", data) : "—")} · _external:_ {(external.Count > 0 ? string.Join(", ", external) : "—")}" : ""));
        }
        if (flowLines.Count > 0)
            sb.AppendLine("\n## Flows\n\nWhat each endpoint reaches: calls, injected dependencies and interface dispatch, hop by hop. " +
                "Reached means the code can get there, not that every request does.\n\n" + string.Join("\n", flowLines));
        var distinctFlow = flowEdges.Distinct().ToList();
        if (distinctFlow.Count is > 0 and <= MaxDiagramEdges * 2)
            sb.AppendLine("\n## Flow\n\n" + Mermaid("graph LR", distinctFlow, x => x));

        // Absolute URLs are external systems (views/context.md), not missing endpoints.
        var unlinked = model.Edges.Where(e => e.Kind == "http" && e.To.StartsWith("http:") && !e.To.Contains("://")).ToList();
        if (unlinked.Count > 0)
        {
            sb.AppendLine("\n## Frontend calls without a matching endpoint\n");
            foreach (var e in unlinked) sb.AppendLine($"- `{e.To[5..]}` from `{nodes.GetValueOrDefault(e.From)?.Name ?? e.From}`");
        }
        return sb.ToString();
    }

    // The returned type and the declared/detected status codes: "`Material`<br>200, 404".
    static string Response(Node n)
    {
        var parts = new List<string>();
        if (n.Returns is not null) parts.Add($"`{Esc(n.Returns)}`");
        if (n.Responses is { Count: > 0 } r) parts.Add(string.Join(", ", r.Select(x => x.Split(' ', 2) is [var code, var type] ? $"{code} `{Esc(type)}`" : x)));
        return parts.Count > 0 ? string.Join("<br>", parts) : "—";
    }

    string FrontendPage()
    {
        var sb = new StringBuilder("# Frontend\n\n");
        var routes = model.Nodes.Where(n => n.Kind == "route").OrderBy(n => n.Route).ToList();
        var routesTo = model.Edges.Where(e => e.Kind == "routes-to").ToLookup(e => e.From, e => e.To);
        var renders = model.Edges.Where(e => e.Kind == "renders").ToLookup(e => e.From, e => e.To);
        var renderedBy = model.Edges.Where(e => e.Kind == "renders").ToLookup(e => e.To, e => e.From);
        if (routes.Count > 0)
        {
            sb.AppendLine("## Routes\n\n| Path | Component |\n|---|---|");
            foreach (var r in routes)
                sb.AppendLine($"| `{r.Route}` | {string.Join(", ", routesTo[r.Id].Where(nodes.ContainsKey).Select(c => ModuleLink(nodes[c])))} |");
            sb.AppendLine();
        }
        var components = model.Nodes.Where(n => n.Kind == "component").OrderBy(n => n.File).ToList();
        if (components.Count > 0)
        {
            var listens = model.Edges.Where(e => e.Kind == "subscribes" && e.Label is not null).ToLookup(e => e.From);
            sb.AppendLine("## Components\n\n| Component | Summary | Props | Emits | Hooks & composables | Renders | Listens to | Used by |\n|---|---|---|---|---|---|---|---|");
            foreach (var c in components)
                sb.AppendLine($"| {ModuleLink(c)} | {Esc(Summary(c) ?? "—")} | {Esc(string.Join(", ", c.Parameters ?? []))} | {string.Join(", ", c.Events ?? [])} | {string.Join(", ", c.Hooks ?? [])} | " +
                    $"{string.Join(", ", renders[c.Id].Where(nodes.ContainsKey).Select(x => nodes[x].Name).Distinct())} | " +
                    $"{string.Join(", ", listens[c.Id].Where(e => nodes.ContainsKey(e.To)).Select(e => $"{nodes[e.To].Name} @{e.Label}").Distinct())} | " +
                    $"{string.Join(", ", renderedBy[c.Id].Where(nodes.ContainsKey).Select(x => nodes[x].Name).Distinct())} |");
        }
        if (routes.Count > 0)
        {
            // Route → page → children → stores/composables → API client → backend endpoint (followed further in api.md).
            var lines = routes.Select(r => (r, Trace(r.Id, stop: n => n.Tags?.Contains("endpoint") == true))).Where(x => x.Item2.Layers.Count > 0)
                .Select(x => $"- `{x.r.Route}` → {Esc(Chain(x.Item2))}").ToList();
            if (lines.Count > 0)
                sb.AppendLine("\n## Flows\n\nFrom each route to the backend endpoints it can reach, hop by hop; see [API](api.md) for what the endpoints do.\n\n" +
                    string.Join("\n", lines));
        }
        if (routes.Count == 0 && components.Count == 0) sb.AppendLine("No Vue frontend found.");
        return sb.ToString();
    }

    string Quality()
    {
        var sb = new StringBuilder("# Quality\n\n");
        sb.AppendLine($"Documentation coverage against the `{config.Profile}` profile: **{Analyzer.Coverage(findings):0}%** of {findings.Count} items that need docs. " +
            "This measures the profile's rules, not compliance with any standard.\n");
        var open = findings.Where(f => f.Status != Status.Documented).OrderByDescending(f => f.Level).ThenBy(f => f.Node.File).ToList();
        sb.AppendLine($"## Undocumented ({open.Count})\n");
        sb.AppendLine("| Level | Item | Status | Missing | Why it needs docs | Tested |\n|---|---|---|---|---|---|");
        foreach (var f in open)
            sb.AppendLine($"| {f.Level} | {SourceLink(f.Node.File, f.Node.Line, $"`{Esc(Display(f.Node))}`")} | {f.Status} | {string.Join(", ", f.Missing)} | {Esc(string.Join("; ", f.Reasons))} | {(f.Tested ? "✓" : "—")} |");
        var ai = findings.Where(f => f.Sections.GetValueOrDefault("summary")?.Origin == Origin.Ai).ToList();
        if (ai.Count > 0)
        {
            sb.AppendLine($"\n## AI drafts ({ai.Count})\n\nDrafted from these facts only; review, then move into the code.\n");
            sb.AppendLine("| Item | Draft | Generated from |\n|---|---|---|");
            foreach (var f in ai)
                sb.AppendLine($"| `{Esc(Display(f.Node))}` | {Esc(f.Sections["summary"].Text)} | " +
                    $"{string.Join(", ", (f.Sections["summary"].From ?? []).Select(id => $"`{Esc(nodes.TryGetValue(id, out var x) ? Display(x) : id)}`"))} |");
        }
        sb.AppendLine("\n## Most complex\n\n| Complexity | Item |\n|---|---|");
        foreach (var n in model.Nodes.Where(n => n.Complexity > 1 && n.Kind != "component").OrderByDescending(n => n.Complexity).Take(20))
            sb.AppendLine($"| {n.Complexity} | {SourceLink(n.File, n.Line, $"`{Esc(Display(n))}`")} |");
        return sb.ToString();
    }

    IEnumerable<Edge> Dependencies() => model.Edges.Where(e => CodeModel.DependencyKinds.Contains(e.Kind))
        .Where(e => nodes.ContainsKey(e.From) && (nodes.ContainsKey(e.To) || e.To.StartsWith("http:")));

    // A member as shown under its type: `Attach(Fixture.Application.MaterialService)`, not the full id.
    static string MemberName(Node m, Node owner) =>
        Display(m).StartsWith(Display(owner)) && Display(m).Length > Display(owner).Length ? Display(m)[(Display(owner).Length + 1)..] : m.Name;

    string Top(string id) => parent.TryGetValue(id, out var p) ? Top(p) : id;

    // A folder's layer is the layer of its first file that matches one.
    Dictionary<string, string?>? folderLayers;
    string? Layer(string folder) => (folderLayers ??= model.Nodes.GroupBy(n => Folder(n.File)).ToDictionary(g => g.Key,
        g => g.Select(n => archConfig.Layers.FirstOrDefault(kv => kv.Value.Any(glob =>
            System.IO.Enumeration.FileSystemName.MatchesSimpleExpression(glob, n.File))).Key).FirstOrDefault(l => l is not null)))
        .GetValueOrDefault(folder);

    // Human-written summary first; an AI draft (clearly marked) only where there is none.
    string? Summary(Node n) => WrittenSummary(n) ?? (drafts.TryGetValue(n.Id, out var d) ? $"🤖 _{Regex.Replace(d, @"\s+", " ")}_" : null);

    string? WrittenSummary(Node n)
    {
        var doc = n.Doc ?? implOf[n.Id].Select(i => nodes.GetValueOrDefault(i)?.Doc).FirstOrDefault(d => d is not null);
        if (doc is null) return null;
        try
        {
            return XElement.Parse(doc).Element("summary") is { } e ? Analyzer.Text(e) : null;
        }
        catch { return null; }
    }

    // Sections the profile requires that DocWizz filled from the model (not written by a person, not AI).
    IEnumerable<(string Name, Section Section)> Derived(Node n) => findingOf.TryGetValue(n.Id, out var f)
        ? f.Sections.Where(kv => kv.Value.Origin is Origin.Fact or Origin.Inferred).Select(kv => (kv.Key.Replace('_', ' '), kv.Value)) : [];

    // ⚠ marks items the analyzer says need (more) docs.
    string Badge(Node n) => findingOf.TryGetValue(n.Id, out var f) && f.Status != Status.Documented ? " ⚠" : "";

    string ModuleLink(Node n) => $"[{n.Name}](modules/{Slug(Folder(n.File))}.md#{Anchor(Top(n.Id))})";
    string Anchor(string id) => Regex.Replace(nodes[id].Name.ToLowerInvariant(), @"[^a-z0-9\- ]", "").Replace(' ', '-');

    string SourceLink(string file, string label) => SourceLink(file, 0, label == "" ? file : label);
    string SourceLink(string file, int line, string label, string sub = "")
    {
        var dir = Path.Combine(outDir, sub);
        var target = Path.GetRelativePath(dir, Path.Combine(root, file)).Replace('\\', '/');
        return $"[{label}]({target}{(line > 0 ? $"#L{line}" : "")})";
    }

    static string Mermaid<T>(string header, IEnumerable<(T From, T To, int Count)> edges, Func<T, string> label) where T : notnull
    {
        var ids = new Dictionary<T, string>();
        string Id(T x) => ids.TryGetValue(x, out var id) ? id : ids[x] = $"n{ids.Count}";
        var sb = new StringBuilder($"```mermaid\n{header}\n");
        var lines = edges.Select(e => $"    {Id(e.From)} -->{(e.Count > 0 ? $"|{e.Count}|" : "")} {Id(e.To)}").ToList();
        foreach (var (x, id) in ids) sb.AppendLine($"    {id}[\"{label(x).Replace("\"", "'")}\"]");
        foreach (var l in lines) sb.AppendLine(l);
        return sb.Append("```\n").ToString();
    }

    static string EndpointLabel(Node n) => $"{n.Tags![1]} /{n.Route?.TrimStart('/')}";
    public static string Display(Node n) => n.Id[(n.Id.IndexOf(':') + 1)..];
    public static string Folder(string file) => Path.GetDirectoryName(file)?.Replace('\\', '/') is { Length: > 0 } d ? d : ".";
    public static string Slug(string folder) => folder == "." ? "root" : Regex.Replace(folder, @"[^A-Za-z0-9.\-]+", "-");
    static string Esc(string s) => s.Replace("|", "\\|").Replace("\n", " ");
}
