using System.Text;
using System.Text.RegularExpressions;
using System.Xml.Linq;

// Writes the docs/ tree. Everything here is derived from the model; nothing is hand-maintained.
partial class Generator(string root, string outDir, CodeModel model, List<DocumentationItem> findings, ArchitectureResult arch, Config config,
    Dictionary<string, string> drafts, Dictionary<string, AiProse.Draft>? overviews = null,
    Dictionary<string, AiProse.Assessment>? assessments = null)
{
    public const string Marker = "<!-- generated by docwizz: edits are overwritten -->";

    // Also write an HTML twin of every page (Html.cs).
    public bool WriteHtml { get; init; }
    public bool RebuildHtml { get; init; }
    public Action<int, int>? OnPageProcessed { get; init; }
    // Repository files (relative, `/`-separated) after exclude:/.gitignore; the deployment view picks its descriptors from them.
    public List<string> Files { get; init; } = [];
    static readonly string[] TopKinds = ["class", "record", "struct", "interface", "type", "enum", "delegate", "component", "module", "store",
        "procedure", "sql-function", "sql-view", "trigger", "table", "migration"];
    const int MaxDiagramEdges = 60;

    readonly ArchitectureConfig archConfig = config.Architecture;
    // Layer and custom rule violations, and security findings (SEC-*, only with security.enabled), shown apart.
    List<Violation> LayerViolations => arch.Violations.Where(v => v.Concern is null).ToList();
    List<Violation> SecurityFindings => arch.Violations.Where(v => v.Concern is not null).ToList();
    readonly Dictionary<string, Node> nodes = model.Nodes.ToDictionary(n => n.Id);
    readonly Dictionary<string, string> parent = model.Edges.Where(e => e.Kind == "contains").ToDictionary(e => e.To, e => e.From);
    readonly ILookup<string, string> children = model.Edges.Where(e => e.Kind == "contains").ToLookup(e => e.From, e => e.To);
    readonly ILookup<string, string> implOf = model.Edges.Where(e => e.Kind == "implements").ToLookup(e => e.From, e => e.To);
    readonly Dictionary<string, DocumentationItem> findingOf = findings.ToDictionary(f => f.Node.Id);
    readonly TestLinks testLinks = new(model);

    // Renders every page, then writes only those whose content changed and removes generated pages that are gone:
    // unchanged pages keep their file (and timestamp), so regenerating after a small change touches only what it affects.
    public (List<string> Pages, List<string> Changed) Run()
    {
        Directory.CreateDirectory(Path.Combine(outDir, "modules"));
        Directory.CreateDirectory(Path.Combine(outDir, "views"));
        var pages = new Dictionary<string, string>();
        void Write(string rel, string body) => pages[rel] = $"{Marker}\n{body}";

        var modules = model.Nodes.Where(n => n.Kind is not ("route" or "project" or "package" or "external" or "config") || parent.ContainsKey(n.Id))
            .GroupBy(n => Folder(n.File)).OrderBy(g => g.Key).ToList();
        foreach (var m in modules) Write($"modules/{Slug(m.Key)}.md", Module(m.Key, m.ToList()));
        Write("index.md", Index(modules.Select(m => m.Key).ToList()));
        Write("architecture.md", ArchitecturePage(modules.Select(m => m.Key).ToList()));
        Write("api.md", Api());
        Write("frontend.md", FrontendPage());
        Write("quality.md", Quality());
        foreach (var (page, _, body) in Views()) Write($"views/{page}.md", body());
        Write("architecture-description.md", DescriptionPage());
        pages["search.json"] = SearchIndex();
        if (WriteHtml)
        {
            var markdown = pages.Where(p => p.Key.EndsWith(".md")).ToDictionary(p => p.Key, p => Html.Title(p.Key, p.Value));
            foreach (var rel in markdown.Keys) pages[Path.ChangeExtension(rel, ".html")] = Html.Page(rel, pages[rel], markdown);
            pages["search.js"] = $"window.docwizzSearch = {pages["search.json"]};\n";
        }

        // Only pages we generated earlier are removed, so renamed/deleted modules don't linger and hand-written ones stay.
        foreach (var f in Directory.EnumerateFiles(outDir, "*.*", SearchOption.AllDirectories).Where(f => f.EndsWith(".md") || f.EndsWith(".html")))
            if (!pages.ContainsKey(Path.GetRelativePath(outDir, f).Replace('\\', '/')) && File.ReadLines(f).Take(2).Contains(Marker)) File.Delete(f);
        var changed = new List<string>();
        var processed = 0;
        foreach (var (rel, content) in pages)
        {
            var file = Path.Combine(outDir, rel);
            // A version refresh rewrites HTML even when it is identical, but only a page whose content differs is "changed".
            var same = File.Exists(file) && File.ReadAllText(file) == content;
            if (!same || (RebuildHtml && rel.EndsWith(".html", StringComparison.OrdinalIgnoreCase))) File.WriteAllText(file, content);
            if (!same) changed.Add(rel);
            OnPageProcessed?.Invoke(++processed, pages.Count);
        }
        return ([.. pages.Keys], changed);
    }

    // Everything a reader might look up, with the page (and anchor) that documents it: for search boxes and tooling.
    string SearchIndex()
    {
        var entries = new List<SearchEntry>();
        void Entry(string name, string kind, string page, string? summary) => entries.Add(new(name, kind, page, summary));
        foreach (var n in model.Nodes.Where(n => TopKinds.Contains(n.Kind) && n.Kind != "module" && Top(n.Id) == n.Id))
            Entry(n.Name, n.Kind, $"modules/{Slug(Folder(n.File))}.md#{Anchor(n.Id)}", WrittenSummary(n));
        foreach (var n in model.Nodes.Where(n => n.Tags?.Contains("endpoint") == true))
            Entry(EndpointLabel(n), "endpoint", "api.md", WrittenSummary(n));
        foreach (var n in model.Nodes.Where(n => n.Kind == "route")) Entry(n.Route ?? n.Name, "route", "frontend.md", null);
        foreach (var n in model.Nodes.Where(n => n.Kind == "config")) Entry(n.Name, "config", "views/deployment.md#configuration", null);
        foreach (var f in model.Nodes.Where(n => n.Kind is not ("route" or "project" or "package" or "external" or "config")).Select(n => Folder(n.File)).Distinct())
            Entry(f, "module", $"modules/{Slug(f)}.md", null);
        return System.Text.Json.JsonSerializer.Serialize(entries.OrderBy(e => e.Name, StringComparer.OrdinalIgnoreCase).ThenBy(e => e.Kind),
            new System.Text.Json.JsonSerializerOptions(System.Text.Json.JsonSerializerDefaults.Web)
            { WriteIndented = true, Encoder = System.Text.Encodings.Web.JavaScriptEncoder.UnsafeRelaxedJsonEscaping });
    }

    record SearchEntry(string Name, string Kind, string Page, string? Summary);

    string Index(List<string> modules)
    {
        var sb = new StringBuilder();
        var kinds = model.Nodes.GroupBy(n => n.Kind).ToDictionary(g => g.Key, g => g.Count());
        sb.AppendLine($"# {Path.GetFileName(Path.GetFullPath(root))}\n");
        sb.AppendLine($"Generated from commit `{model.Commit ?? "unknown"}`.\n");
        sb.AppendLine("| | |\n|---|---|");
        foreach (var (label, kind) in new[] { ("Classes & records", "class"), ("Methods", "method"), ("Frontend functions", "function") })
        {
            var n = kind == "class" ? kinds.GetValueOrDefault("class") + kinds.GetValueOrDefault("record") : kinds.GetValueOrDefault(kind);
            if (n > 0) sb.AppendLine($"| {label} | {n} |");
        }
        sb.AppendLine($"| Documentation coverage (profile `{config.Profile}`) | {Analyzer.Coverage(findings):0}% |");
        sb.AppendLine($"| Doc quality (written docs without quality flags) | {Analyzer.Quality(findings):0}% |");
        sb.AppendLine($"| Critical documentation gaps | {findings.Count(Analyzer.IsCritical)} |");
        sb.AppendLine($"| Architecture violations / cycles | {LayerViolations.Count} / {arch.Cycles.Count} |");
        if (config.Security.Enabled) sb.AppendLine($"| Security findings ([review](architecture-description.md#security)) | {SecurityFindings.Count} |");
        sb.AppendLine();
        if (drafts.Count > 0)
            sb.AppendLine($"🤖 marks {drafts.Count} AI-drafted summaries for code that has no docs yet — review them, then move them into the code.\n");
        sb.AppendLine("- [Architecture description](architecture-description.md)\n- [Architecture](architecture.md)\n- [API endpoints](api.md)\n" +
            "- [Frontend](frontend.md)\n- [Quality](quality.md)\n");
        if (Technology().ToList() is { Count: > 0 } tech)
            sb.AppendLine("## Technology\n\n" + string.Join("\n", tech.Select(t => $"- {t}")) + "\n");
        var blocks = Roles.Select(r => (r.Label, Count: model.Nodes.Count(n => n.Kind == r.Match || n.Tags?.Contains(r.Match) == true)))
            .Where(r => r.Count > 0).ToList();
        if (blocks.Count > 0)
            sb.AppendLine("## Building blocks\n\n| Role | Count |\n|---|---|\n" + string.Join("\n", blocks.Select(b => $"| {b.Label} | {b.Count} |")) + "\n");
        sb.AppendLine("## Modules\n");
        foreach (var m in modules) sb.AppendLine($"- [{m}](modules/{Slug(m)}.md) — {Layer(m) ?? "no layer"}");
        return sb.ToString();
    }

    // Kind or tag → label, in reading order (backend, then frontend).
    static readonly (string Label, string Match)[] Roles = [("Controllers", "controller"), ("API endpoints", "endpoint"),
        ("Services", "service"), ("Repositories", "repository"), ("Entities", "entity"), ("DbContexts", "dbcontext"),
        ("Background services", "background-service"), ("Hosted services", "hosted"), ("Middleware", "middleware"), ("SignalR hubs", "hub"), ("Options", "options"),
        ("Stored procedures", "procedure"), ("SQL tables", "table"), ("Migrations", "migration"),
        ("UI components", "component"), ("Views", "view"), ("Stores", "store"), ("Composables", "composable"), ("Routes", "route")];

    // Well-known packages → what they tell a reader about the stack. Anything else is in views/context.md.
    // ponytail: a short curated list; extend it (or read it from config) when a project's stack goes unnamed.
    static readonly (string Package, string Label)[] KnownPackages = [
        ("Microsoft.EntityFrameworkCore.SqlServer", "Entity Framework Core, SQL Server"),
        ("Npgsql.EntityFrameworkCore.PostgreSQL", "Entity Framework Core, PostgreSQL"),
        ("Microsoft.EntityFrameworkCore.Sqlite", "Entity Framework Core, SQLite"),
        ("Pomelo.EntityFrameworkCore.MySql", "Entity Framework Core, MySQL"),
        ("Microsoft.EntityFrameworkCore", "Entity Framework Core"), ("Dapper", "Dapper"), ("Npgsql", "PostgreSQL"),
        ("MediatR", "MediatR"), ("MassTransit", "MassTransit"), ("Hangfire.Core", "Hangfire"), ("Serilog", "Serilog"),
        ("Swashbuckle.AspNetCore", "Swagger / OpenAPI"), ("Microsoft.AspNetCore.OpenApi", "OpenAPI"),
        ("Microsoft.AspNetCore.SignalR", "SignalR"), ("vue", "Vue"), ("nuxt", "Nuxt"), ("pinia", "Pinia"), ("vuex", "Vuex"),
        ("vue-router", "Vue Router"), ("axios", "axios"), ("vite", "Vite"), ("vuetify", "Vuetify"), ("quasar", "Quasar"),
        ("primevue", "PrimeVue"), ("element-plus", "Element Plus"), ("typescript", "TypeScript")];

    // From the project files only: SDK, target frameworks, well-known packages with their declared version.
    IEnumerable<string> Technology()
    {
        foreach (var p in model.Nodes.Where(n => n.Kind == "project" && n.Tags?.Contains("dotnet") == true))
        {
            var sdk = p.Tags!.FirstOrDefault(t => t.StartsWith("Microsoft.NET.Sdk"));
            var kind = sdk switch
            {
                "Microsoft.NET.Sdk.Web" => "ASP.NET Core", "Microsoft.NET.Sdk.Worker" => ".NET worker",
                "Microsoft.NET.Sdk.Razor" => "Razor class library", "Microsoft.NET.Sdk.BlazorWebAssembly" => "Blazor WebAssembly",
                _ => ".NET",
            };
            var tfms = p.Tags!.Where(t => t.StartsWith("net")).ToList();
            var role = p.Tags!.FirstOrDefault(t => t is "executable" or "library" or "test");
            var folder = p.Tags!.FirstOrDefault(t => t.StartsWith("sln:"))?[4..];
            yield return $"`{p.Name}`: {kind}{(tfms.Count > 0 ? $" on {string.Join(", ", tfms)}" : "")}" +
                (role is null ? "" : $" — {role}") + (folder is null ? "" : $", solution folder `{folder}`");
        }
        foreach (var p in model.Nodes.Where(n => n.Kind == "project" && n.Tags?.Any(t => t is "maven" or "gradle") == true))
        {
            var spring = model.Edges.Any(e => e.Kind == "depends-on" && e.From == p.Id && e.To.Contains(":org.springframework.boot:"));
            yield return $"`{p.Name}`: {(spring ? "Spring Boot" : "Java")} ({p.Tags![0]}) — {p.Tags.ElementAtOrDefault(1) ?? "library"}";
        }
        var versions = model.Edges.Where(e => e.Kind == "depends-on").GroupBy(e => e.To).ToDictionary(g => g.Key, g => g.First().Label);
        var packages = model.Nodes.Where(n => n.Kind == "package").ToDictionary(n => n.Name, n => n.Id);
        var named = new List<string>();  // "Entity Framework Core, PostgreSQL" already names EF Core and PostgreSQL
        foreach (var (package, label) in KnownPackages)
            if (packages.TryGetValue(package, out var id) && !named.Any(l => l.Contains(label)))
            {
                named.Add(label);
                yield return versions.GetValueOrDefault(id) is { } v ? $"{label} ({v})" : label;
            }
    }

    string ArchitecturePage(List<string> modules)
    {
        var sb = new StringBuilder("# Architecture\n\n");
        // Layer graph: any HTTP call is a dependency on `http`. Module graph: HTTP calls point at the endpoint's module.
        var deps = Dependencies().Select(d => (From: Folder(nodes[d.From].File),
            To: nodes.TryGetValue(d.To, out var t) ? Folder(t.File) : null, Http: d.Kind == "http")).ToList();

        sb.AppendLine("Views: " + string.Join(" · ", Views().Select(v => $"[{v.Title}](views/{v.Page}.md)")) + "\n");
        sb.AppendLine("## Layers\n");
        sb.AppendLine("Actual dependencies between layers (edge label = number of references). Allowed per config: ");
        sb.AppendLine(string.Join(", ", archConfig.Allow.Select(kv => $"`{kv.Key} → {(kv.Value.Count > 0 ? string.Join("/", kv.Value) : "∅")}`")) + ".\n");
        var layerEdges = arch.LayerDependencies.Select(d => (d.From, d.To, d.Count));
        sb.AppendLine(Mermaid("graph TD", layerEdges, x => x));

        sb.AppendLine("## Modules\n");
        var moduleEdges = deps.Where(d => d.To is not null && d.To != d.From)
            .GroupBy(d => (d.From, To: d.To!)).Select(g => (g.Key.From, g.Key.To, g.Count())).ToList();
        sb.AppendLine(moduleEdges.Count <= MaxDiagramEdges * 2
            ? Mermaid("graph LR", moduleEdges, x => x)
            : $"_{moduleEdges.Count} module dependencies — too many to draw; see each module page._\n");

        if (archConfig.Rules.Count > 0)
        {
            sb.AppendLine($"## Custom rules ({archConfig.Rules.Count})\n\nUser-defined in `docwizz.yaml` (`architecture.rules`), checked next to the built-in ARCH-001…004.\n");
            sb.AppendLine("| Rule | Severity | Rule says | Why | Violations |\n|---|---|---|---|---|");
            foreach (var r in archConfig.Rules)
                sb.AppendLine($"| {r.Id} | {(archConfig.Severity.GetValueOrDefault(r.Id) ?? r.Severity ?? "medium").ToLowerInvariant()} | {Esc(Architecture.Describe(r))} | " +
                    $"{Esc(r.Description ?? "—")} | {arch.Violations.Count(v => v.Rule == r.Id)} |");
            sb.AppendLine();
        }
        var violations = LayerViolations;
        sb.AppendLine($"## Violations ({violations.Count})\n");
        if (violations.Count == 0) sb.AppendLine("None.\n");
        else
        {
            sb.AppendLine("| Rule | Layers | Severity | From | To | Example |\n|---|---|---|---|---|---|");
            foreach (var v in violations.OrderByDescending(v => v.Severity))
                sb.AppendLine($"| {v.Rule}{(v.Custom ? " (custom)" : "")} | {v.FromLayer} → {v.ToLayer} | {v.Severity.ToString().ToLowerInvariant()} | {SourceLink(v.FromFile, "")} | `{v.To}` | {Esc(v.Example)} |");
            sb.AppendLine();
        }
        sb.AppendLine($"## Cycles ({arch.Cycles.Count})\n");
        foreach (var c in arch.Cycles) sb.AppendLine($"- {string.Join(" ↔ ", c.Select(m => $"[{m}](modules/{Slug(m)}.md)"))}");
        if (arch.Cycles.Count == 0) sb.AppendLine("None.");

        // Coupling: fan-in (Ca) = modules depending on this one, fan-out (Ce) = modules it depends on,
        // instability Ce / (Ca + Ce): 0 = everything leans on it, 1 = it leans on everything.
        var fanIn = moduleEdges.GroupBy(e => e.To).ToDictionary(g => g.Key, g => g.Count());
        var fanOut = moduleEdges.GroupBy(e => e.From).ToDictionary(g => g.Key, g => g.Count());
        var coupled = fanIn.Keys.Union(fanOut.Keys).Select(m => (Module: m, In: fanIn.GetValueOrDefault(m), Out: fanOut.GetValueOrDefault(m)))
            .OrderByDescending(c => c.In + c.Out).ThenBy(c => c.Module).ToList();
        if (coupled.Count > 0)
        {
            sb.AppendLine("\n## Coupling\n\nFan-in: modules that depend on this one. Fan-out: modules it depends on. " +
                "Instability = fan-out / (fan-in + fan-out); stable modules (near 0) are costly to change, so they should not depend on unstable ones.\n");
            sb.AppendLine("| Module | Layer | Fan-in | Fan-out | Instability |\n|---|---|---|---|---|");
            foreach (var c in coupled.Take(MaxListed * 2))
                sb.AppendLine($"| [{c.Module}](modules/{Slug(c.Module)}.md) | {Layer(c.Module) ?? "—"} | {c.In} | {c.Out} | {(double)c.Out / (c.In + c.Out):0.00} |");
            if (coupled.Count > MaxListed * 2) sb.AppendLine($"\n_… {coupled.Count - MaxListed * 2} more modules._");
        }

        var risks = Risks().ToList();
        sb.AppendLine($"\n## Risks ({risks.Count})\n");
        sb.AppendLine(risks.Count > 0 ? string.Join("\n", risks.Select(r => $"- {r}")) : "None detected.");
        return sb.ToString();
    }

    const int ApiLogicComplexity = 8;

    // Design risks that break no configured rule but tend to hurt: entities leaking through the API, business logic in
    // the API layer, domain code bound to external packages.
    IEnumerable<string> Risks()
    {
        var entities = model.Nodes.Where(n => n.Tags?.Contains("entity") == true).ToList();
        foreach (var e in model.Nodes.Where(n => n.Tags?.Contains("endpoint") == true).OrderBy(n => n.Route))
        {
            var types = (e.Responses ?? []).Append(e.Returns ?? "");
            var leaked = entities.Where(x => types.Any(t => Regex.IsMatch(t, $@"\b{Regex.Escape(x.Name)}\b"))).Select(x => $"`{x.Name}`").ToList();
            if (leaked.Count > 0)
                yield return $"Entity exposed: `{EndpointLabel(e)}` returns {string.Join(", ", leaked)} — persistence shape becomes the API contract; return a DTO";
        }
        foreach (var n in model.Nodes.Where(n => n.Kind is "method" or "endpoint" && n.Complexity >= ApiLogicComplexity
                && (Layer(Folder(n.File)) == "api" || n.Tags?.Contains("endpoint") == true)).OrderByDescending(n => n.Complexity))
            yield return $"Logic in the API layer: `{Esc(ShortName(n))}` has complexity {n.Complexity} — move the decisions into the application layer " +
                $"({SourceLink(n.File, n.Line, Path.GetFileName(n.File))})";
        foreach (var g in model.Edges.Where(e => e.Kind == "uses-namespace" && nodes.TryGetValue(e.From, out var n) && Layer(Folder(n.File)) == "domain")
                .GroupBy(e => e.To[3..]).OrderBy(g => g.Key))
            yield return $"Domain depends on `{g.Key}` ({string.Join(", ", g.Select(e => $"`{nodes[e.From].Name}`").Distinct())}) — " +
                "the domain layer should need nothing outside the language and its own code";
    }

    string Api()
    {
        var sb = new StringBuilder("# API endpoints\n\n");
        var callers = model.Edges.Where(e => e.Kind == "http").ToLookup(e => e.To, e => e.From);
        var endpoints = model.Nodes.Where(n => n.Tags?.Contains("endpoint") == true)
            .OrderBy(n => n.Route?.TrimStart('/')).ThenBy(n => n.Tags![1]).ToList();
        sb.AppendLine(endpoints.Count == 0 ? "No endpoints found.\n"
            : "| Method | Route | Summary | Input | Response | Authorization | Handler | Called from |\n|---|---|---|---|---|---|---|---|");
        foreach (var n in endpoints)
        {
            var from = callers[n.Id].Select(c => nodes.TryGetValue(c, out var cn) ? $"`{cn.Name}`" : c).Distinct();
            var input = string.Join("<br>", (n.Parameters ?? []).Select(p => $"`{Esc(p)}`"));
            var auth = n.Tags!.Contains("anonymous") ? "anonymous" : n.Tags.Contains("authorize") ? "required" : "—";
            sb.AppendLine($"| {n.Tags![1]} | `/{n.Route?.TrimStart('/')}` | {Esc(Summary(n) ?? "—")} | {(input == "" ? "—" : input)} | " +
                $"{Response(n)} | {auth} | {SourceLink(n.File, n.Line, $"{Path.GetFileName(n.File)}:{n.Line}")} | {string.Join(", ", from)} |");
        }
        // Middleware in registration order, per place that configures it (a project's top-level code, Startup.Configure).
        foreach (var g in model.Edges.Where(e => e.Kind == "pipeline").GroupBy(e => e.From))
        {
            var at = nodes.TryGetValue(g.Key, out var owner) ? owner.Kind == "project" ? $"project `{owner.Name}`" : $"`{Display(owner)}`" : g.Key;
            sb.AppendLine($"\n## Request pipeline ({at})\n\nMiddleware in the order it is registered; each request passes through it top to bottom.\n");
            var i = 0;
            foreach (var e in g)
                sb.AppendLine($"{++i}. {(nodes.TryGetValue(e.To, out var m) ? $"{ModuleLink(m)} (`UseMiddleware`)" : $"`{e.To["pipeline:".Length..]}`")}");
        }
        // Each endpoint's path: frontend callers → endpoint → handler (controller) → services → data → external systems.
        var flowLines = new List<string>();
        var flowEdges = new List<(string From, string To, int Count)>();
        foreach (var n in endpoints)
        {
            var trace = Trace(n.Id);
            var handler = parent.TryGetValue(n.Id, out var owner) ? owner : null;
            var label = EndpointLabel(n);
            foreach (var c in callers[n.Id].Where(nodes.ContainsKey)) flowEdges.Add((nodes[c].Name, label, 0));
            if (handler is not null) flowEdges.Add((label, nodes[handler].Name, 0));
            foreach (var (from, to) in trace.Steps)
                flowEdges.Add((from == n.Id ? handler is null ? label : nodes[handler].Name : UnitLabel(from), UnitLabel(to), 0));
            if (trace.Layers.Count == 0) continue;
            var data = Reached(trace, x => x.Tags?.Contains("dbcontext") == true).Select(x => x.Name).ToList();
            var external = Reached(trace, x => x.Kind == "external").Select(ExternalLabel).ToList();
            flowLines.Add($"- `{label}`: {(handler is null ? "" : $"{nodes[handler].Name} → ")}{Esc(Chain(trace))}" +
                (data.Count + external.Count > 0 ? $"  \n  _data:_ {(data.Count > 0 ? string.Join(", ", data) : "—")} · _external:_ {(external.Count > 0 ? string.Join(", ", external) : "—")}" : ""));
        }
        if (flowLines.Count > 0)
            sb.AppendLine("\n## Flows\n\nWhat each endpoint reaches: calls, injected dependencies and interface dispatch, hop by hop. " +
                "Reached means the code can get there, not that every request does.\n\n" + string.Join("\n", flowLines));
        var distinctFlow = flowEdges.Distinct().ToList();
        if (distinctFlow.Count is > 0 and <= MaxDiagramEdges * 2)
            sb.AppendLine("\n## Flow\n\n" + Mermaid("graph LR", distinctFlow, x => x));

        // Absolute URLs are external systems (views/context.md), not missing endpoints.
        var unlinked = model.Edges.Where(e => e.Kind == "http" && e.To.StartsWith("http:") && !e.To.Contains("://")).ToList();
        if (unlinked.Count > 0)
        {
            sb.AppendLine("\n## Frontend calls without a matching endpoint\n");
            foreach (var e in unlinked) sb.AppendLine($"- `{e.To[5..]}` from `{nodes.GetValueOrDefault(e.From)?.Name ?? e.From}`");
        }
        return sb.ToString();
    }

    // The returned type and the declared/detected status codes: "`Material`<br>200, 404".
    static string Response(Node n)
    {
        var parts = new List<string>();
        if (n.Returns is not null) parts.Add($"`{Esc(n.Returns)}`");
        if (n.Responses is { Count: > 0 } r) parts.Add(string.Join(", ", r.Select(x => x.Split(' ', 2) is [var code, var type] ? $"{code} `{Esc(type)}`" : x)));
        return parts.Count > 0 ? string.Join("<br>", parts) : "—";
    }

    string FrontendPage()
    {
        var sb = new StringBuilder("# Frontend\n\n");
        var routes = model.Nodes.Where(n => n.Kind == "route").OrderBy(n => n.Route).ToList();
        var routesTo = model.Edges.Where(e => e.Kind == "routes-to").ToLookup(e => e.From, e => e.To);
        var renders = model.Edges.Where(e => e.Kind == "renders").ToLookup(e => e.From, e => e.To);
        var renderedBy = model.Edges.Where(e => e.Kind == "renders").ToLookup(e => e.To, e => e.From);
        if (routes.Count > 0)
        {
            sb.AppendLine("## Routes\n\n| Path | Component |\n|---|---|");
            foreach (var r in routes)
                sb.AppendLine($"| `{r.Route}` | {string.Join(", ", routesTo[r.Id].Where(nodes.ContainsKey).Select(c => ModuleLink(nodes[c])))} |");
            sb.AppendLine();
        }
        var components = model.Nodes.Where(n => n.Kind == "component").OrderBy(n => n.File).ToList();
        if (components.Count > 0)
        {
            var listens = model.Edges.Where(e => e.Kind == "subscribes" && e.Label is not null).ToLookup(e => e.From);
            sb.AppendLine("## Components\n\n| Component | Summary | Props | Emits | Hooks & composables | Renders | Listens to | Used by |\n|---|---|---|---|---|---|---|---|");
            foreach (var c in components)
                sb.AppendLine($"| {ModuleLink(c)} | {Esc(Summary(c) ?? "—")} | {Esc(string.Join(", ", c.Parameters ?? []))} | {string.Join(", ", c.Events ?? [])} | {string.Join(", ", c.Hooks ?? [])} | " +
                    $"{string.Join(", ", renders[c.Id].Where(nodes.ContainsKey).Select(x => nodes[x].Name).Distinct())} | " +
                    $"{string.Join(", ", listens[c.Id].Where(e => nodes.ContainsKey(e.To)).Select(e => $"{nodes[e.To].Name} @{e.Label}").Distinct())} | " +
                    $"{string.Join(", ", renderedBy[c.Id].Where(nodes.ContainsKey).Select(x => nodes[x].Name).Distinct())} |");
        }
        if (routes.Count > 0)
        {
            // Route → page → children → stores/composables → API client → backend endpoint (followed further in api.md).
            var lines = routes.Select(r => (r, Trace(r.Id, stop: n => n.Tags?.Contains("endpoint") == true))).Where(x => x.Item2.Layers.Count > 0)
                .Select(x => $"- `{x.r.Route}` → {Esc(Chain(x.Item2))}").ToList();
            if (lines.Count > 0)
                sb.AppendLine("\n## Flows\n\nFrom each route to the backend endpoints it can reach, hop by hop; see [API](api.md) for what the endpoints do.\n\n" +
                    string.Join("\n", lines));
        }
        if (routes.Count == 0 && components.Count == 0) sb.AppendLine("No frontend (Vue, React, Angular) found.");
        return sb.ToString();
    }

    string Quality()
    {
        var sb = new StringBuilder("# Quality\n\n");
        sb.AppendLine($"Documentation coverage against the `{config.Profile}` profile: **{Analyzer.Coverage(findings):0}%** of {findings.Count} items that need docs. " +
            "This measures the profile's rules, not compliance with any standard.\n");
        var written = Analyzer.WithWrittenDocs(findings);
        sb.AppendLine($"Doc quality: **{Analyzer.Quality(findings):0}%** of {written.Count} items with written docs have no quality flags.\n");
        var open = findings.Where(f => f.Status != Status.Documented).OrderByDescending(f => f.Level).ThenBy(f => f.Node.File).ToList();
        sb.AppendLine($"## Undocumented ({open.Count})\n");
        sb.AppendLine("_Tested_: test code is linked to the item, directly or through its interface, an implementation or a member. " +
            "That is a structural link, not code coverage.\n");
        sb.AppendLine("| Level | Item | Status | Missing | Why it needs docs | Tested |\n|---|---|---|---|---|---|");
        foreach (var f in open)
            sb.AppendLine($"| {f.Level} | {SourceLink(f.Node.File, f.Node.Line, $"`{Esc(Display(f.Node))}`")} | {f.Status} | {string.Join(", ", f.Missing)} | {Esc(string.Join("; ", f.Reasons))} | {(f.Tested ? "✓" : "—")} |");
        var flagged = findings.Where(f => f.Flags is { Count: > 0 }).OrderBy(f => f.Node.File).ThenBy(f => f.Node.Line).ToList();
        if (flagged.Count > 0)
        {
            sb.AppendLine($"\n## Doc quality ({flagged.Count})\n\nWritten documentation that contradicts the code (fact) or looks like it adds nothing (inferred).\n");
            sb.AppendLine("| Item | Rule | Basis | Problem |\n|---|---|---|---|");
            foreach (var f in flagged)
                foreach (var q in f.Flags!)
                    sb.AppendLine($"| {SourceLink(f.Node.File, f.Node.Line, $"`{Esc(Display(f.Node))}`")} | {q.Rule} | {(q.Origin == Origin.Fact ? "fact" : "inferred")} | {Esc(q.Detail)} |");
        }
        var rated = findings.Where(f => assessments?.ContainsKey(f.Node.Id) == true)
            .OrderBy(f => assessments![f.Node.Id].Score).ThenBy(f => f.Node.File).ThenBy(f => f.Node.Line).ToList();
        if (rated.Count > 0)
        {
            sb.AppendLine($"\n## Usefulness 🤖 ({rated.Count})\n\nA self-hosted model's rating of written docs, from 1 (says nothing the name doesn't) " +
                "to 5 (purpose, constraints, side effects and errors). AI-assessed and advisory: not part of doc quality, never fails `check`.\n");
            sb.AppendLine("| Item | Score | Missing | Note |\n|---|---|---|---|");
            foreach (var f in rated)
            {
                var a = assessments![f.Node.Id];
                sb.AppendLine($"| {SourceLink(f.Node.File, f.Node.Line, $"`{Esc(Display(f.Node))}`")} | {a.Score} | {Esc(string.Join(", ", a.Missing))} | {Esc(a.Note)} |");
            }
        }
        var ai = findings.Where(f => f.Sections.GetValueOrDefault("summary")?.Origin == Origin.Ai).ToList();
        if (ai.Count > 0)
        {
            sb.AppendLine($"\n## AI drafts ({ai.Count})\n\nDrafted from these facts only; review, then move into the code.\n");
            sb.AppendLine("| Item | Draft | Generated from |\n|---|---|---|");
            foreach (var f in ai)
                sb.AppendLine($"| `{Esc(Display(f.Node))}` | {Esc(f.Sections["summary"].Text)} | " +
                    $"{string.Join(", ", (f.Sections["summary"].From ?? []).Select(id => $"`{Esc(nodes.TryGetValue(id, out var x) ? Display(x) : id)}`"))} |");
        }
        sb.AppendLine("\n## Most complex\n\n| Complexity | Item |\n|---|---|");
        foreach (var n in model.Nodes.Where(n => n.Complexity > 1 && n.Kind != "component").OrderByDescending(n => n.Complexity).Take(20))
            sb.AppendLine($"| {n.Complexity} | {SourceLink(n.File, n.Line, $"`{Esc(Display(n))}`")} |");
        return sb.ToString();
    }

    IEnumerable<Edge> Dependencies() => model.Edges.Where(e => CodeModel.DependencyKinds.Contains(e.Kind))
        .Where(e => nodes.ContainsKey(e.From) && (nodes.ContainsKey(e.To) || e.To.StartsWith("http:")));

    // A member as shown under its type: `Attach(Fixture.Application.MaterialService)`, not the full id.
    static string MemberName(Node m, Node owner) =>
        Display(m).StartsWith(Display(owner)) && Display(m).Length > Display(owner).Length ? Display(m)[(Display(owner).Length + 1)..] : m.Name;

    // The top-level symbol a member belongs to. A TS class/interface/type/enum stands on its own inside its file module.
    string Top(string id) => parent.TryGetValue(id, out var p)
        && !(nodes[p].Kind == "module" && nodes[id].Kind is "class" or "interface" or "type" or "enum") ? Top(p) : id;

    // A folder's layer is the layer of its first file that matches one.
    Dictionary<string, string?>? folderLayers;
    string? Layer(string folder) => (folderLayers ??= model.Nodes.GroupBy(n => Folder(n.File)).ToDictionary(g => g.Key,
        g => g.Select(n => archConfig.Layers.FirstOrDefault(kv => kv.Value.Any(glob =>
            System.IO.Enumeration.FileSystemName.MatchesSimpleExpression(glob, n.File))).Key).FirstOrDefault(l => l is not null)))
        .GetValueOrDefault(folder);

    // Human-written summary first; an AI draft (clearly marked) only where there is none.
    string? Summary(Node n) => WrittenSummary(n) ?? (drafts.TryGetValue(n.Id, out var d) ? $"🤖 _{Regex.Replace(d, @"\s+", " ")}_" : null);

    string? WrittenSummary(Node n)
    {
        var doc = n.Doc ?? implOf[n.Id].Select(i => nodes.GetValueOrDefault(i)?.Doc).FirstOrDefault(d => d is not null);
        if (doc is null) return null;
        try
        {
            return XElement.Parse(doc).Element("summary") is { } e ? Analyzer.Text(e) : null;
        }
        catch { return null; }
    }

    // Sections DocWizz filled from the model, and AI-drafted ones beyond the summary (marked 🤖 where shown).
    IEnumerable<(string Name, Section Section)> Derived(Node n) => findingOf.TryGetValue(n.Id, out var f)
        ? f.Sections.Where(kv => kv.Value.Origin is Origin.Fact or Origin.Inferred || kv.Value.Origin == Origin.Ai && kv.Key != "summary")
            .Select(kv => (kv.Key.Replace('_', ' '), kv.Value)) : [];

    // ⚠ marks items the analyzer says need (more) docs.
    string Badge(Node n) => findingOf.TryGetValue(n.Id, out var f) && f.Status != Status.Documented ? " ⚠" : "";

    string ModuleLink(Node n) => $"[{n.Name}](modules/{Slug(Folder(n.File))}.md#{Anchor(Top(n.Id))})";
    string Anchor(string id) => Regex.Replace(nodes[id].Name.ToLowerInvariant(), @"[^a-z0-9\- ]", "").Replace(' ', '-');

    string SourceLink(string file, string label) => SourceLink(file, 0, label == "" ? file : label);
    string SourceLink(string file, int line, string label, string sub = "")
    {
        var dir = Path.Combine(outDir, sub);
        var target = Path.GetRelativePath(dir, Path.Combine(root, file)).Replace('\\', '/');
        return $"[{label}]({target}{(line > 0 ? $"#L{line}" : "")})";
    }

    static string Mermaid<T>(string header, IEnumerable<(T From, T To, int Count)> edges, Func<T, string> label) where T : notnull
    {
        var ids = new Dictionary<T, string>();
        string Id(T x) => ids.TryGetValue(x, out var id) ? id : ids[x] = $"n{ids.Count}";
        var sb = new StringBuilder($"```mermaid\n{header}\n");
        var lines = edges.Select(e => $"    {Id(e.From)} -->{(e.Count > 0 ? $"|{e.Count}|" : "")} {Id(e.To)}").ToList();
        if (lines.Count == 0) return "None.\n";
        foreach (var (x, id) in ids) sb.AppendLine($"    {id}[\"{label(x).Replace("\"", "'")}\"]");
        foreach (var l in lines) sb.AppendLine(l);
        return sb.Append("```\n").ToString();
    }

    public static string EndpointLabel(Node n) => $"{n.Tags![1]} /{n.Route?.TrimStart('/')}";
    public static string Display(Node n) => n.Id[(n.Id.IndexOf(':') + 1)..];
    public static string Folder(string file) => Path.GetDirectoryName(file)?.Replace('\\', '/') is { Length: > 0 } d ? d : ".";
    public static string Slug(string folder) => folder == "." ? "root" : Regex.Replace(folder, @"[^A-Za-z0-9.\-]+", "-");
    static string Esc(string s) => s.Replace("|", "\\|").Replace("\n", " ");
}
