using System.Text;
using System.Text.RegularExpressions;
using System.Xml.Linq;

// Writes the docs/ tree. Everything here is derived from the model; nothing is hand-maintained.
class Generator(string root, string outDir, CodeModel model, List<DocumentationItem> findings, ArchitectureResult arch, Config config,
    Dictionary<string, string> drafts)
{
    public const string Marker = "<!-- generated by docwizz: edits are overwritten -->";
    static readonly string[] TopKinds = ["class", "record", "struct", "interface", "enum", "component", "module", "store"];
    const int MaxDiagramEdges = 60;

    readonly ArchitectureConfig archConfig = config.Architecture;
    readonly Dictionary<string, Node> nodes = model.Nodes.ToDictionary(n => n.Id);
    readonly Dictionary<string, string> parent = model.Edges.Where(e => e.Kind == "contains").ToDictionary(e => e.To, e => e.From);
    readonly ILookup<string, string> children = model.Edges.Where(e => e.Kind == "contains").ToLookup(e => e.From, e => e.To);
    readonly ILookup<string, string> implOf = model.Edges.Where(e => e.Kind == "implements").ToLookup(e => e.From, e => e.To);
    readonly Dictionary<string, DocumentationItem> findingOf = findings.ToDictionary(f => f.Node.Id);

    public List<string> Run()
    {
        Directory.CreateDirectory(Path.Combine(outDir, "modules"));
        // Remove only pages we generated earlier, so renamed/deleted modules don't linger.
        foreach (var f in Directory.EnumerateFiles(outDir, "*.md", SearchOption.AllDirectories))
            if (File.ReadLines(f).FirstOrDefault() == Marker) File.Delete(f);

        var written = new List<string>();
        void Write(string rel, string body)
        {
            File.WriteAllText(Path.Combine(outDir, rel), $"{Marker}\n{body}");
            written.Add(rel);
        }

        var modules = model.Nodes.Where(n => n.Kind is not ("route" or "endpoint" or "project" or "package") || parent.ContainsKey(n.Id))
            .GroupBy(n => Folder(n.File)).OrderBy(g => g.Key).ToList();
        foreach (var m in modules) Write($"modules/{Slug(m.Key)}.md", Module(m.Key, m.ToList()));
        Write("index.md", Index(modules.Select(m => m.Key).ToList()));
        Write("architecture.md", ArchitecturePage(modules.Select(m => m.Key).ToList()));
        Write("api.md", Api());
        Write("frontend.md", FrontendPage());
        Write("quality.md", Quality());
        return written;
    }

    string Index(List<string> modules)
    {
        var sb = new StringBuilder();
        var kinds = model.Nodes.GroupBy(n => n.Kind).ToDictionary(g => g.Key, g => g.Count());
        sb.AppendLine($"# {Path.GetFileName(Path.GetFullPath(root))}\n");
        sb.AppendLine($"Generated from commit `{model.Commit ?? "unknown"}`.\n");
        sb.AppendLine("| | |\n|---|---|");
        foreach (var (label, kind) in new[] { ("Classes & records", "class"), ("Methods", "method"), ("API endpoints", "endpoint"),
                     ("Vue components", "component"), ("Frontend functions", "function"), ("Routes", "route") })
        {
            var n = kind == "class" ? kinds.GetValueOrDefault("class") + kinds.GetValueOrDefault("record") : kinds.GetValueOrDefault(kind);
            if (n > 0) sb.AppendLine($"| {label} | {n} |");
        }
        sb.AppendLine($"| Documentation coverage (profile `{config.Profile}`) | {Analyzer.Coverage(findings):0}% |");
        sb.AppendLine($"| Critical documentation gaps | {findings.Count(Analyzer.IsCritical)} |");
        sb.AppendLine($"| Architecture violations / cycles | {arch.Violations.Count} / {arch.Cycles.Count} |\n");
        if (drafts.Count > 0)
            sb.AppendLine($"🤖 marks {drafts.Count} AI-drafted summaries for code that has no docs yet — review them, then move them into the code.\n");
        sb.AppendLine("- [Architecture](architecture.md)\n- [API endpoints](api.md)\n- [Frontend](frontend.md)\n- [Quality](quality.md)\n");
        sb.AppendLine("## Modules\n");
        foreach (var m in modules) sb.AppendLine($"- [{m}](modules/{Slug(m)}.md) — {Layer(m) ?? "no layer"}");
        return sb.ToString();
    }

    string ArchitecturePage(List<string> modules)
    {
        var sb = new StringBuilder("# Architecture\n\n");
        // Layer graph: any HTTP call is a dependency on `http`. Module graph: HTTP calls point at the endpoint's module.
        var deps = Dependencies().Select(d => (From: Folder(nodes[d.From].File),
            To: nodes.TryGetValue(d.To, out var t) ? Folder(t.File) : null, Http: d.Kind == "http")).ToList();

        sb.AppendLine("## Layers\n");
        sb.AppendLine("Actual dependencies between layers (edge label = number of references). Allowed per config: ");
        sb.AppendLine(string.Join(", ", archConfig.Allow.Select(kv => $"`{kv.Key} → {(kv.Value.Count > 0 ? string.Join("/", kv.Value) : "∅")}`")) + ".\n");
        var layerEdges = deps.Select(d => (From: Layer(d.From), To: d.Http ? "http" : d.To is null ? null : Layer(d.To)))
            .Where(d => d.From is not null && d.To is not null && d.From != d.To)
            .GroupBy(d => d).Select(g => (g.Key.From!, g.Key.To!, g.Count()));
        sb.AppendLine(Mermaid("graph TD", layerEdges, x => x));

        sb.AppendLine("## Modules\n");
        var moduleEdges = deps.Where(d => d.To is not null && d.To != d.From)
            .GroupBy(d => (d.From, To: d.To!)).Select(g => (g.Key.From, g.Key.To, g.Count())).ToList();
        sb.AppendLine(moduleEdges.Count <= MaxDiagramEdges * 2
            ? Mermaid("graph LR", moduleEdges, x => x)
            : $"_{moduleEdges.Count} module dependencies — too many to draw; see each module page._\n");

        sb.AppendLine($"## Violations ({arch.Violations.Count})\n");
        if (arch.Violations.Count == 0) sb.AppendLine("None.\n");
        else
        {
            sb.AppendLine("| Rule | Layers | From | To | Example |\n|---|---|---|---|---|");
            foreach (var v in arch.Violations)
                sb.AppendLine($"| {v.Rule} | {v.FromLayer} → {v.ToLayer} | {SourceLink(v.FromFile, "")} | `{v.To}` | {Esc(v.Example)} |");
            sb.AppendLine();
        }
        sb.AppendLine($"## Cycles ({arch.Cycles.Count})\n");
        foreach (var c in arch.Cycles) sb.AppendLine($"- {string.Join(" ↔ ", c.Select(m => $"[{m}](modules/{Slug(m)}.md)"))}");
        if (arch.Cycles.Count == 0) sb.AppendLine("None.");
        return sb.ToString();
    }

    string Api()
    {
        var sb = new StringBuilder("# API endpoints\n\n");
        var callers = model.Edges.Where(e => e.Kind == "http").ToLookup(e => e.To, e => e.From);
        var endpoints = model.Nodes.Where(n => n.Tags?.Contains("endpoint") == true)
            .OrderBy(n => n.Route?.TrimStart('/')).ThenBy(n => n.Tags![1]).ToList();
        sb.AppendLine("| Method | Route | Summary | Input | Response | Authorization | Handler | Called from |\n|---|---|---|---|---|---|---|---|");
        foreach (var n in endpoints)
        {
            var from = callers[n.Id].Select(c => nodes.TryGetValue(c, out var cn) ? $"`{cn.Name}`" : c).Distinct();
            var input = string.Join("<br>", (n.Parameters ?? []).Select(p => $"`{Esc(p)}`"));
            var auth = n.Tags!.Contains("anonymous") ? "anonymous" : n.Tags.Contains("authorize") ? "required" : "—";
            sb.AppendLine($"| {n.Tags![1]} | `/{n.Route?.TrimStart('/')}` | {Esc(Summary(n) ?? "—")} | {(input == "" ? "—" : input)} | " +
                $"{(n.Returns is null ? "—" : $"`{Esc(n.Returns)}`")} | {auth} | {SourceLink(n.File, n.Line, $"{Path.GetFileName(n.File)}:{n.Line}")} | {string.Join(", ", from)} |");
        }
        var unlinked = model.Edges.Where(e => e.Kind == "http" && e.To.StartsWith("http:")).ToList();
        if (unlinked.Count > 0)
        {
            sb.AppendLine("\n## Frontend calls without a matching endpoint\n");
            foreach (var e in unlinked) sb.AppendLine($"- `{e.To[5..]}` from `{nodes.GetValueOrDefault(e.From)?.Name ?? e.From}`");
        }
        return sb.ToString();
    }

    string FrontendPage()
    {
        var sb = new StringBuilder("# Frontend\n\n");
        var routes = model.Nodes.Where(n => n.Kind == "route").OrderBy(n => n.Route).ToList();
        var routesTo = model.Edges.Where(e => e.Kind == "routes-to").ToLookup(e => e.From, e => e.To);
        var renders = model.Edges.Where(e => e.Kind == "renders").ToLookup(e => e.From, e => e.To);
        var renderedBy = model.Edges.Where(e => e.Kind == "renders").ToLookup(e => e.To, e => e.From);
        if (routes.Count > 0)
        {
            sb.AppendLine("## Routes\n\n| Path | Component |\n|---|---|");
            foreach (var r in routes)
                sb.AppendLine($"| `{r.Route}` | {string.Join(", ", routesTo[r.Id].Where(nodes.ContainsKey).Select(c => ModuleLink(nodes[c])))} |");
            sb.AppendLine();
        }
        var components = model.Nodes.Where(n => n.Kind == "component").OrderBy(n => n.File).ToList();
        if (components.Count > 0)
        {
            sb.AppendLine("## Components\n\n| Component | Summary | Props | Renders | Used by |\n|---|---|---|---|---|");
            foreach (var c in components)
                sb.AppendLine($"| {ModuleLink(c)} | {Esc(Summary(c) ?? "—")} | {c.Params ?? 0} | " +
                    $"{string.Join(", ", renders[c.Id].Where(nodes.ContainsKey).Select(x => nodes[x].Name).Distinct())} | " +
                    $"{string.Join(", ", renderedBy[c.Id].Where(nodes.ContainsKey).Select(x => nodes[x].Name).Distinct())} |");
        }
        if (routes.Count == 0 && components.Count == 0) sb.AppendLine("No Vue frontend found.");
        return sb.ToString();
    }

    string Quality()
    {
        var sb = new StringBuilder("# Quality\n\n");
        sb.AppendLine($"Documentation coverage against the `{config.Profile}` profile: **{Analyzer.Coverage(findings):0}%** of {findings.Count} items that need docs. " +
            "This measures the profile's rules, not compliance with any standard.\n");
        var open = findings.Where(f => f.Status != Status.Documented).OrderByDescending(f => f.Level).ThenBy(f => f.Node.File).ToList();
        sb.AppendLine($"## Undocumented ({open.Count})\n");
        sb.AppendLine("| Level | Item | Status | Missing | Why it needs docs | Tested |\n|---|---|---|---|---|---|");
        foreach (var f in open)
            sb.AppendLine($"| {f.Level} | {SourceLink(f.Node.File, f.Node.Line, $"`{Esc(Display(f.Node))}`")} | {f.Status} | {string.Join(", ", f.Missing)} | {Esc(string.Join("; ", f.Reasons))} | {(f.Tested ? "✓" : "—")} |");
        sb.AppendLine("\n## Most complex\n\n| Complexity | Item |\n|---|---|");
        foreach (var n in model.Nodes.Where(n => n.Complexity > 1 && n.Kind != "component").OrderByDescending(n => n.Complexity).Take(20))
            sb.AppendLine($"| {n.Complexity} | {SourceLink(n.File, n.Line, $"`{Esc(Display(n))}`")} |");
        return sb.ToString();
    }

    string Module(string folder, List<Node> members)
    {
        var sb = new StringBuilder($"# {folder}\n\n");
        if (Layer(folder) is { } layer) sb.AppendLine($"Layer: **{layer}**\n");

        var tops = members.Where(n => TopKinds.Contains(n.Kind) && !parent.ContainsKey(n.Id)).OrderBy(n => n.Name).ToList();
        var topIds = tops.Select(t => t.Id).ToHashSet();
        var deps = Dependencies().Select(d => (From: Top(d.From), To: Top(d.To)))
            .Where(d => d.From != d.To && nodes.ContainsKey(d.To) && (topIds.Contains(d.From) || topIds.Contains(d.To)))
            .Distinct().ToList();

        string ModuleOf(string id) => Folder(nodes[id].File);
        var uses = deps.Where(d => topIds.Contains(d.From) && !topIds.Contains(d.To)).Select(d => ModuleOf(d.To)).Distinct().Order().ToList();
        var usedBy = deps.Where(d => topIds.Contains(d.To) && !topIds.Contains(d.From)).Select(d => ModuleOf(d.From)).Distinct().Order().ToList();
        if (uses.Count > 0) sb.AppendLine("Depends on: " + string.Join(", ", uses.Select(m => $"[{m}]({Slug(m)}.md)")) + "\n");
        if (usedBy.Count > 0) sb.AppendLine("Used by: " + string.Join(", ", usedBy.Select(m => $"[{m}]({Slug(m)}.md)")) + "\n");

        var outgoing = deps.Where(d => topIds.Contains(d.From)).Select(d => (d.From, d.To, 0)).ToList();
        if (outgoing.Count is > 0 and <= MaxDiagramEdges)
            sb.AppendLine(Mermaid("graph LR", outgoing, id => nodes[id].Name));

        foreach (var t in tops)
        {
            sb.AppendLine($"## {t.Name}\n");
            sb.AppendLine($"_{t.Kind}_ · {SourceLink(t.File, t.Line, Path.GetFileName(t.File), fromModule: true)}{Badge(t)}\n");
            if (Summary(t) is { } s) sb.AppendLine(s + "\n");
            if (t.Kind == "component" && t.Params > 0) sb.AppendLine($"Props: {string.Join(", ", t.Parameters ?? [$"{t.Params}"])}\n");
            if (t.Events is { Count: > 0 }) sb.AppendLine($"Emits: {string.Join(", ", t.Events)}\n");
            foreach (var (name, section) in Derived(t)) sb.AppendLine($"- **{name}** _({section.Origin.ToString().ToLowerInvariant()})_: {Esc(section.Text)}");
            if (Derived(t).Any()) sb.AppendLine();

            var ms = children[t.Id].Select(nodes.GetValueOrDefault).OfType<Node>()
                .Where(m => m.Kind is "method" or "function" or "endpoint" && m.Visibility is "public" or "protected" or "internal" or null)
                .OrderBy(m => m.Line).ToList();
            if (ms.Count == 0) continue;
            sb.AppendLine("| Member | Summary | Derived from code | Complexity |\n|---|---|---|---|");
            foreach (var m in ms)
                sb.AppendLine($"| {SourceLink(m.File, m.Line, $"`{Esc(Display(m).Split('.').Last())}`", fromModule: true)}{Badge(m)} | {Esc(Summary(m) ?? "")} | " +
                    $"{Esc(string.Join("; ", Derived(m).Select(d => $"{d.Name}{(d.Section.Origin == Origin.Inferred ? " (inferred)" : "")}: {d.Section.Text}")))} | {m.Complexity} |");
            sb.AppendLine();
        }
        var files = members.Select(m => m.File).Distinct().Order().ToList();
        sb.AppendLine($"---\n_Generated from {members.Count} symbols in {string.Join(", ", files.Select(f => SourceLink(f, 0, f, fromModule: true)))} " +
            $"(commit `{model.Commit ?? "unknown"}`, profile `{config.Profile}`). Sections marked _fact_ are read from the code, " +
            "_inferred_ come from heuristics, 🤖 marks AI drafts._");
        return sb.ToString();
    }

    IEnumerable<Edge> Dependencies() => model.Edges.Where(e => CodeModel.DependencyKinds.Contains(e.Kind))
        .Where(e => nodes.ContainsKey(e.From) && (nodes.ContainsKey(e.To) || e.To.StartsWith("http:")));

    string Top(string id) => parent.TryGetValue(id, out var p) ? Top(p) : id;

    // A folder's layer is the layer of its first file that matches one.
    Dictionary<string, string?>? folderLayers;
    string? Layer(string folder) => (folderLayers ??= model.Nodes.GroupBy(n => Folder(n.File)).ToDictionary(g => g.Key,
        g => g.Select(n => archConfig.Layers.FirstOrDefault(kv => kv.Value.Any(glob =>
            System.IO.Enumeration.FileSystemName.MatchesSimpleExpression(glob, n.File))).Key).FirstOrDefault(l => l is not null)))
        .GetValueOrDefault(folder);

    // Human-written summary first; an AI draft (clearly marked) only where there is none.
    string? Summary(Node n) => WrittenSummary(n) ?? (drafts.TryGetValue(n.Id, out var d) ? $"🤖 _{Regex.Replace(d, @"\s+", " ")}_" : null);

    string? WrittenSummary(Node n)
    {
        var doc = n.Doc ?? implOf[n.Id].Select(i => nodes.GetValueOrDefault(i)?.Doc).FirstOrDefault(d => d is not null);
        if (doc is null) return null;
        try
        {
            var text = XElement.Parse(doc).Element("summary")?.Value;
            return text is null ? null : Regex.Replace(text, @"\s+", " ").Trim();
        }
        catch { return null; }
    }

    // Sections the profile requires that DocWizz filled from the model (not written by a person, not AI).
    IEnumerable<(string Name, Section Section)> Derived(Node n) => findingOf.TryGetValue(n.Id, out var f)
        ? f.Sections.Where(kv => kv.Value.Origin is Origin.Fact or Origin.Inferred).Select(kv => (kv.Key.Replace('_', ' '), kv.Value)) : [];

    // ⚠ marks items the analyzer says need (more) docs.
    string Badge(Node n) => findingOf.TryGetValue(n.Id, out var f) && f.Status != Status.Documented ? " ⚠" : "";

    string ModuleLink(Node n) => $"[{n.Name}](modules/{Slug(Folder(n.File))}.md#{Anchor(Top(n.Id))})";
    string Anchor(string id) => Regex.Replace(nodes[id].Name.ToLowerInvariant(), @"[^a-z0-9\- ]", "").Replace(' ', '-');

    string SourceLink(string file, string label) => SourceLink(file, 0, label == "" ? file : label);
    string SourceLink(string file, int line, string label, bool fromModule = false)
    {
        var dir = fromModule ? Path.Combine(outDir, "modules") : outDir;
        var target = Path.GetRelativePath(dir, Path.Combine(root, file)).Replace('\\', '/');
        return $"[{label}]({target}{(line > 0 ? $"#L{line}" : "")})";
    }

    static string Mermaid<T>(string header, IEnumerable<(T From, T To, int Count)> edges, Func<T, string> label) where T : notnull
    {
        var ids = new Dictionary<T, string>();
        string Id(T x) => ids.TryGetValue(x, out var id) ? id : ids[x] = $"n{ids.Count}";
        var sb = new StringBuilder($"```mermaid\n{header}\n");
        var lines = edges.Select(e => $"    {Id(e.From)} -->{(e.Count > 0 ? $"|{e.Count}|" : "")} {Id(e.To)}").ToList();
        foreach (var (x, id) in ids) sb.AppendLine($"    {id}[\"{label(x).Replace("\"", "'")}\"]");
        foreach (var l in lines) sb.AppendLine(l);
        return sb.Append("```\n").ToString();
    }

    public static string Display(Node n) => n.Id[(n.Id.IndexOf(':') + 1)..];
    public static string Folder(string file) => Path.GetDirectoryName(file)?.Replace('\\', '/') is { Length: > 0 } d ? d : ".";
    public static string Slug(string folder) => folder == "." ? "root" : Regex.Replace(folder, @"[^A-Za-z0-9.\-]+", "-");
    static string Esc(string s) => s.Replace("|", "\\|").Replace("\n", " ");
}
