using System.Text.RegularExpressions;
using Markdig;

// HTML twins of the generated Markdown, written next to it: the same tree, so relative links to sources keep working.
// Links between generated pages go to their HTML twin; Mermaid blocks render with mermaid.js (from a CDN, the code stays
// readable offline); search.js holds the search index as a script, which works from file:// where fetch() does not.
// Every page carries the whole site in its sidebar, so each one stands alone and opens from disk.
static class Html
{
    static readonly (string Page, string Label)[] Top =
        [("index.md", "Overview"), ("architecture.md", "Architecture"), ("api.md", "API"), ("frontend.md", "Frontend"), ("quality.md", "Quality")];
    // Pinned: a new Mermaid release must not change every diagram unannounced.
    public const string MermaidUrl = "https://cdn.jsdelivr.net/npm/mermaid@11.4.1/dist/mermaid.esm.min.mjs";

    // The page's `# ` heading, else its file name.
    public static string Title(string rel, string markdown)
    {
        var heading = Regex.Match(markdown, @"^# (.+)$", RegexOptions.Multiline);
        return heading.Success ? heading.Groups[1].Value.Trim() : Path.GetFileNameWithoutExtension(rel);
    }

    static readonly MarkdownPipeline Pipeline = new MarkdownPipelineBuilder()
        .UseAutoIdentifiers(Markdig.Extensions.AutoIdentifiers.AutoIdentifierOptions.GitHub) // same anchors as the Markdown links
        .UseAdvancedExtensions().Build();

    // `pages`: every generated Markdown page (relative, `/`-separated) and its title.
    public static string Page(string rel, string markdown, IReadOnlyDictionary<string, string> pages)
    {
        var dir = Path.GetDirectoryName(rel)?.Replace('\\', '/') ?? "";
        var body = Markdown.ToHtml(markdown.Replace(Generator.Marker, ""), Pipeline);
        body = Regex.Replace(body, @"href=""([^""#:?]+)\.md(#[^""]*)?""", m =>
        {
            var target = Path.GetRelativePath(".", Path.Combine(dir, m.Groups[1].Value + ".md")).Replace('\\', '/');
            return pages.ContainsKey(target) ? $"href=\"{m.Groups[1].Value}.html{m.Groups[2].Value}\"" : m.Value;
        });
        var up = string.Concat(Enumerable.Repeat("../", rel.Count(c => c == '/')));
        string Link(string page, string label) =>
            $"<a href=\"{up}{Path.ChangeExtension(page, ".html")}\"{(page == rel ? " aria-current=\"page\"" : "")}>{Enc(label)}</a>";
        var nav = string.Concat(Top.Select(n => Link(n.Page, n.Label)));
        var title = Title(rel, markdown);
        var side = Sidebar(rel, body, pages, Link);
        var toc = TableOfContents(body);
        var category = rel.StartsWith("modules/") ? "Module" : rel.StartsWith("views/") ? "Architecture view" : "Documentation";
        var breadcrumb = rel.Contains('/') ? rel.Split('/')[0] : "Pages";
        return $$"""
            <!doctype html>
            {{Generator.Marker}}
            <html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
            <title>{{System.Net.WebUtility.HtmlEncode(title)}}</title>
            <style>
            {{HtmlDesign.Css}}
            </style></head><body>
            <a class="skip" href="#content">Skip to content</a>
            <div class="reading-progress" id="reading-progress" aria-hidden="true"></div>
            <header><button class="icon-button" id="nav-toggle" type="button" aria-label="Open navigation" aria-controls="site-nav" aria-expanded="false">☰</button><a class="brand" href="{{up}}index.html"><span class="brand-mark" aria-hidden="true">DW</span><span class="brand-name">Doc<span>Wizz</span></span></a><nav aria-label="Primary">{{nav}}</nav>
            <div class="header-actions"><div class="search"><input id="q" type="search" placeholder="Search docs..." aria-label="Search"
              role="combobox" aria-expanded="false" aria-controls="hits" aria-autocomplete="list" autocomplete="off"><kbd aria-hidden="true">/</kbd><ul id="hits" role="listbox"></ul></div><button class="icon-button" id="theme-toggle" type="button" aria-label="Switch theme" title="Switch theme">☾</button></div></header>
            <div class="layout">
            <nav class="side" id="site-nav" aria-label="Site"><div class="side-top">Explore <button class="icon-button" id="nav-close" type="button" aria-label="Close navigation">×</button></div><div class="filter-wrap"><input id="side-filter" type="search" placeholder="Filter pages" aria-label="Filter navigation pages" autocomplete="off"></div><p class="side-empty" id="side-empty" hidden>No pages match.</p>{{side}}</nav>
            <main id="content">
            <div class="breadcrumbs"><a href="{{up}}index.html">Docs</a><span aria-hidden="true">/</span><span>{{Enc(breadcrumb)}}</span></div>
            <span class="report-label">{{Enc(category)}}</span>
            {{body}}
            <footer class="generator">Generated by docwizz {{Enc(AppVersion.Number)}}</footer>
            </main>
            <aside class="toc" aria-label="On this page">{{toc}}</aside>
            </div>
            <script src="{{up}}search.js"></script>
            <script>{{HtmlDesign.Script}}</script>
            <script>
            // Exact names first, then prefixes, then substrings; shorter names before longer ones.
            const q = document.getElementById('q'), hits = document.getElementById('hits');
            let active = -1;
            const rank = (name, t) => { const n = name.toLowerCase(); return n === t ? 0 : n.startsWith(t) ? 1 : n.includes(t) ? 2 : -1; };
            function render() {
              const t = q.value.trim().toLowerCase();
              active = -1; q.removeAttribute('aria-activedescendant');
              const items = (t.length < 2 ? [] : (window.docwizzSearch || []).map(e => [rank(e.name, t), e]).filter(r => r[0] >= 0)
                .sort((a, b) => a[0] - b[0] || a[1].name.length - b[1].name.length || a[1].name.localeCompare(b[1].name))
                .slice(0, 20)).map(([, e], i) => {
                  const li = document.createElement('li'), a = document.createElement('a'), k = document.createElement('small');
                  li.id = 'hit-' + i; li.setAttribute('role', 'option'); li.setAttribute('aria-selected', 'false');
                  a.href = '{{up}}' + e.page.replace(/\.md(#|$)/, '.html$1'); a.textContent = e.name; a.tabIndex = -1; k.textContent = ' ' + e.kind;
                  a.append(k); li.append(a); return li;
                });
              if (t.length >= 2 && !items.length) {
                const li = document.createElement('li'); li.className = 'none'; li.textContent = 'No matches'; items.push(li);
              }
              hits.replaceChildren(...items); q.setAttribute('aria-expanded', String(items.length > 0));
            }
            function select(i) {
              const options = hits.querySelectorAll('[role=option]');
              if (!options.length) return;
              active = (i + options.length) % options.length;
              options.forEach((o, j) => o.setAttribute('aria-selected', String(j === active)));
              options[active].scrollIntoView({ block: 'nearest' }); q.setAttribute('aria-activedescendant', options[active].id);
            }
            q.addEventListener('input', render);
            q.addEventListener('keydown', e => {
              if (e.key === 'ArrowDown') { e.preventDefault(); select(active + 1); }
              else if (e.key === 'ArrowUp') { e.preventDefault(); select(active < 0 ? -1 : active - 1); }
              else if (e.key === 'Enter') { const a = hits.querySelectorAll('[role=option] a')[Math.max(active, 0)]; if (a) location.href = a.href; }
              else if (e.key === 'Escape') { q.value = ''; render(); q.blur(); }
            });
            document.addEventListener('keydown', e => {
              const el = document.activeElement;
              if (e.key === '/' && el !== q && !/^(INPUT|TEXTAREA|SELECT)$/.test(el.tagName) && !el.isContentEditable) { e.preventDefault(); q.focus(); }
            });
            </script>
            <script type="module">
            if (document.querySelector('.mermaid')) {
              const { default: mermaid } = await import('{{MermaidUrl}}');
              mermaid.initialize({ startOnLoad: false, theme: matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'default' });
              await mermaid.run();
            }
            </script>
            </body></html>
            """;
    }

    // Explicit headings improve reading navigation on long reports.
    static string TableOfContents(string body)
    {
        var headings = Regex.Matches(body, @"<h2 id=""([^""]+)"">(.*?)</h2>", RegexOptions.Singleline)
            .Select(m => (Id: Enc(m.Groups[1].Value), Label: Regex.Replace(m.Groups[2].Value, "<[^>]+>", "")))
            .ToList();
        if (headings.Count == 0) return "";
        return "<div class=\"toc-inner\"><div class=\"toc-title\">On this page</div><ul>"
            + string.Concat(headings.Select(h => $"<li><a href=\"#{h.Id}\">{h.Label}</a></li>")) + "</ul></div>";
    }

    static string Enc(string s) => System.Net.WebUtility.HtmlEncode(s);

    // Pages, Views and Modules, the group holding this page open; above them this page's `##` sections when there are 3+.
    static string Sidebar(string rel, string body, IReadOnlyDictionary<string, string> pages, Func<string, string, string> link)
    {
        string Group(string name, IReadOnlyList<(string Page, string Label)> items, bool open) => items.Count == 0 ? "" :
            $"<details{(open || items.Any(i => i.Page == rel) ? " open" : "")}><summary>{name}</summary><ul>"
            + string.Concat(items.Select(i => $"<li>{link(i.Page, i.Label)}</li>")) + "</ul></details>";
        List<(string, string)> Under(string folder) => pages.Where(p => p.Key.StartsWith(folder + "/"))
            .OrderBy(p => p.Value, StringComparer.Ordinal).ThenBy(p => p.Key, StringComparer.Ordinal).Select(p => (p.Key, p.Value)).ToList();
        var topPages = Top.Where(t => pages.ContainsKey(t.Page))
            .Concat(pages.Where(p => !p.Key.Contains('/') && Top.All(t => t.Page != p.Key)).OrderBy(p => p.Key, StringComparer.Ordinal).Select(p => (p.Key, p.Value)))
            .ToList();
        // Markdig's auto identifiers: <h2 id="...">text</h2>; the text is already HTML, only tags are dropped.
        var sections = Regex.Matches(body, @"<h2 id=""([^""]+)"">(.*?)</h2>")
            .Select(m => $"<li><a href=\"#{m.Groups[1].Value}\">{Regex.Replace(m.Groups[2].Value, "<[^>]+>", "")}</a></li>").ToList();
        var toc = "";
        return toc + Group("Pages", topPages, true) + Group("Views", Under("views"), false) + Group("Modules", Under("modules"), false);
    }
}
