using System.Text.Json;
using System.Text.RegularExpressions;

// `docwizz product check`: whether a generated product draft is consistent with its template, its sources and the code
// as it is now, before a person reviews it. It checks references and freshness, not content: whether a statement is
// true, a decision right or a product approvable stays a human judgement, and nothing here says otherwise.
static class ProductCheck
{
    // Severity: error fails the check (exit 1); warning is reported only.
    public record Finding(string Rule, string Severity, string? Section, string Message);

    // Text in a project statement that reads like an instruction to a model. Statements are only ever sent as data
    // (ProductSynthesis), but such text is worth a human look before it goes anywhere.
    static readonly Regex Instructions = new(@"\b(ignore (all |the )?(previous|above)|disregard|system prompt|you are (now )?an?|act as|new instructions)\b",
        RegexOptions.IgnoreCase | RegexOptions.CultureInvariant);

    // Every finding for the draft at `draft` (its report sits next to it), errors and warnings, in rule order.
    public static List<Finding> Run(string root, ProductTemplate template, CodeModel model, ProjectContext? project, string draft)
    {
        var findings = new List<Finding>();
        var catalog = ProductDraft.Catalog(template, model, project);

        // PROD-001: a required section without evidence is open. Allowed in a draft, visible in the check.
        foreach (var (section, evidence) in catalog.Where(c => c.Section.Required && c.Evidence.Count == 0))
            findings.Add(new("PROD-001", "warning", section.Id, $"required section '{section.Title}' has no evidence and is OFFEN"));

        // PROD-002: every project statement's source must exist in the repository.
        foreach (var s in project?.Statements ?? [])
            if (!File.Exists(Path.Combine(root, s.Source)))
                findings.Add(new("PROD-002", "error", s.SectionId, $"statement source {s.Source} does not exist"));

        // PROD-003: products this one depends on need a draft of their own.
        var products = Path.GetDirectoryName(Path.GetFullPath(draft))!;
        foreach (var dependency in template.Dependencies)
            if (!File.Exists(Path.Combine(products, dependency + ".md")))
                findings.Add(new("PROD-003", "error", null, $"depends on product '{dependency}', which has no draft in {Path.GetRelativePath(root, products)}"));

        // PROD-005: statements that read like instructions to a model.
        foreach (var s in project?.Statements ?? [])
            if (Instructions.IsMatch(s.Text))
                findings.Add(new("PROD-005", "warning", s.SectionId, $"statement from {s.Source} reads like an instruction to a model: \"{s.Text}\" (it is only sent as data)"));

        // PROD-004: the draft and its report exist, are docwizz's, and still match the evidence.
        var report = Path.ChangeExtension(draft, ".evidence.json");
        if (!File.Exists(draft) || !File.ReadLines(draft).Take(2).Contains("<!-- generated by docwizz product -->"))
        {
            findings.Add(new("PROD-004", "error", null, $"{Path.GetRelativePath(root, draft)} is missing or not generated by docwizz product; run docwizz product first"));
            return findings;
        }
        JsonElement written;
        try { written = JsonDocument.Parse(File.ReadAllText(report)).RootElement; }
        catch (Exception e) when (e is IOException or JsonException)
        {
            findings.Add(new("PROD-004", "error", null, $"{Path.GetRelativePath(root, report)} is missing or unreadable; run docwizz product again"));
            return findings;
        }
        var sections = written.TryGetProperty("sections", out var list) && list.ValueKind == JsonValueKind.Array
            ? list.EnumerateArray().ToDictionary(x => x.GetProperty("id").GetString()!) : [];
        foreach (var (section, evidence) in catalog)
        {
            var before = sections.TryGetValue(section.Id, out var s) && s.TryGetProperty("evidence", out var e)
                ? e.EnumerateArray().Select(x => $"{x.GetProperty("id").GetString()}|{x.GetProperty("text").GetString()}|{x.GetProperty("source").GetString()}").ToList() : [];
            if (!before.SequenceEqual(evidence.Select(x => $"{x.Id}|{x.Text}|{x.Source}")))
                findings.Add(new("PROD-004", "error", section.Id, $"evidence of '{section.Title}' changed since the draft was generated; run docwizz product again"));
        }

        // PROD-006: every 🤖 sentence in the draft cites only evidence of its own section.
        var ids = sections.ToDictionary(kv => kv.Key, kv => kv.Value.TryGetProperty("evidence", out var e)
            ? e.EnumerateArray().Select(x => x.GetProperty("id").GetString()!).ToHashSet() : []);
        var titles = template.Sections.ToDictionary(x => x.Title, x => x.Id);
        string? current = null;
        foreach (var line in File.ReadLines(draft))
        {
            if (line.StartsWith("## ")) current = titles.GetValueOrDefault(line[3..].Trim());
            else if (line.StartsWith("🤖 ") && current is not null)
                foreach (var cited in Regex.Matches(line, @"\[(E\d+(?:, E\d+)*)\]").SelectMany(m => m.Groups[1].Value.Split(", ")).Distinct())
                    if (!ids.GetValueOrDefault(current, []).Contains(cited))
                        findings.Add(new("PROD-006", "error", current, $"an AI sentence cites {cited}, which is not evidence of this section"));
        }
        return findings;
    }

    // The findings for a terminal, errors first, with the verdict and what the check does not cover.
    public static void Report(ProductTemplate template, List<Finding> findings, TextWriter o)
    {
        o.WriteLine($"Product {template.ProductId} ({template.XtVariant} {template.XtVersion})");
        foreach (var f in findings.OrderBy(f => f.Severity == "error" ? 0 : 1).ThenBy(f => f.Rule, StringComparer.Ordinal))
            o.WriteLine($"  {f.Rule}  {f.Severity,-7}  {(f.Section is null ? "" : $"[{f.Section}] ")}{f.Message}");
        var errors = findings.Count(f => f.Severity == "error");
        o.WriteLine();
        o.WriteLine(errors == 0 ? $"product check: PASS ({findings.Count} warnings)" : $"product check: FAIL — {errors} errors, {findings.Count - errors} warnings");
        o.WriteLine("This checks references and freshness only. Content, decisions and approval need human review.");
    }
}
